using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Services.Implementations;
public sealed class AttachmentFileService(ISupportingService metadata,IWebHostEnvironment environment):IAttachmentFileService
{
 private const long MaxBytes=10*1024*1024;private static readonly HashSet<string> Allowed=new(StringComparer.OrdinalIgnoreCase){".pdf",".jpg",".jpeg",".png",".doc",".docx",".xls",".xlsx"};
 private string Root=>Path.GetFullPath(Path.Combine(environment.ContentRootPath,"App_Data","attachments"));
 public async Task<StoredProcedureResult?> UploadAsync(string entityType,long entityId,IFormFile file,CancellationToken ct){if(file.Length<=0||file.Length>MaxBytes)throw new ArgumentException("Attachment must be between 1 byte and 10 MB.");var ext=Path.GetExtension(file.FileName);if(!Allowed.Contains(ext))throw new ArgumentException("Unsupported attachment type.");var relative=Path.Combine(entityType.Trim().ToUpperInvariant(),entityId.ToString(),$"{Guid.NewGuid():N}{ext.ToLowerInvariant()}");var path=SafePath(relative);Directory.CreateDirectory(Path.GetDirectoryName(path)!);await using(var output=new FileStream(path,FileMode.CreateNew,FileAccess.Write,FileShare.None,81920,true))await file.CopyToAsync(output,ct);try{var result=await metadata.AddAttachmentAsync(new(){EntityType=entityType,EntityId=entityId,FileName=Path.GetFileName(relative),OriginalFileName=Path.GetFileName(file.FileName),StorageKey=relative,FileExtension=ext,MimeType=string.IsNullOrWhiteSpace(file.ContentType)?"application/octet-stream":file.ContentType,FileSize=file.Length,DocumentType="SUPPORTING_DOCUMENT"},ct);if(result?.ResultCode!=ResultCodes.Success)File.Delete(path);return result;}catch{File.Delete(path);throw;}}
 public async Task<AttachmentFileContent?> OpenAsync(long attachmentId,string entityType,long entityId,CancellationToken ct){var item=(await metadata.GetAttachmentsAsync(entityType,entityId,ct)).SingleOrDefault(x=>x.Id==attachmentId);if(item is null)return null;var path=SafePath(item.StorageKey);if(!File.Exists(path))return null;return new(new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.Read,81920,true),item.MimeType??"application/octet-stream",item.OriginalFileName);}
 private string SafePath(string relative){var path=Path.GetFullPath(Path.Combine(Root,relative));if(!path.StartsWith(Root+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Invalid attachment storage reference.");return path;}
}
