using System.ComponentModel.DataAnnotations;
namespace JamunaBank.Procurement.API.DTOs;
public sealed class SaveRequisitionRequest{[Required,StringLength(2000)]public string Justification{get;init;}=string.Empty;[MinLength(1)]public IReadOnlyList<SaveRequisitionItemRequest> Items{get;init;}=[];}
public sealed class SaveRequisitionItemRequest{[Range(1,long.MaxValue)]public long AssetId{get;init;}[Required]public string RequisitionType{get;init;}=string.Empty;[Range(typeof(decimal),"0.01","9999999999999999")]public decimal Quantity{get;init;}[Range(typeof(decimal),"0.01","9999999999999999")]public decimal EstimatedUnitPrice{get;init;}[Required,StringLength(2000)]public string PurposeJustification{get;init;}=string.Empty;[StringLength(2000)]public string? AdditionalSpecificationRequirement{get;init;}public IReadOnlyList<SaveRequisitionSpecificationRequest> DynamicSpecifications{get;init;}=[];public ReplacementInfoRequest? ReplacementInfo{get;init;}}
public sealed class SaveRequisitionSpecificationRequest{[Range(1,long.MaxValue)]public long SpecId{get;init;}public string? TextValue{get;init;}public decimal? NumberValue{get;init;}public DateOnly? DateValue{get;init;}public bool? BoolValue{get;init;}public IReadOnlyList<long> OptionIds{get;init;}=[];}
public sealed class ReplacementInfoRequest{[StringLength(100)]public string? AssetTag{get;init;}[StringLength(100)]public string? Serial{get;init;}[Required,StringLength(2000)]public string CurrentCondition{get;init;}=string.Empty;[StringLength(2000)]public string? AdditionalInfo{get;init;}}
public sealed record RequisitionSummaryDto(long Id,string Number,DateTime RequestedDate,string Justification,decimal TotalEstimatedAmount,string Status,int ItemCount);
public sealed record RequisitionDetailDto(long Id,string Number,string RequestedByEmployeeId,long RequestedOrgUnitId,string OrgUnitName,DateTime RequestedDate,string Justification,decimal TotalEstimatedAmount,string Status,IReadOnlyList<RequisitionItemDto> Items,IReadOnlyList<AttachmentDto> Attachments);
public sealed record RequisitionItemDto(long Id,long AssetId,string AssetName,string RequisitionType,decimal Quantity,decimal EstimatedUnitPrice,string PurposeJustification,string? AdditionalSpecificationRequirement,IReadOnlyList<RequisitionSpecificationValueDto> DynamicSpecifications,ReplacementInfoDto? ReplacementInfo);
public sealed record RequisitionSpecificationValueDto(long SpecId,string Name,string Type,string? TextValue,decimal? NumberValue,DateOnly? DateValue,bool? BoolValue,IReadOnlyList<SelectedSpecificationOptionDto> Options);
public sealed record SelectedSpecificationOptionDto(long OptionId,string Value);
public sealed record ReplacementInfoDto(string? AssetTag,string? Serial,string CurrentCondition,string? AdditionalInfo);
public sealed record AttachmentDto(long Id,string EntityType,long EntityId,string FileName,string OriginalFileName,string? Extension,string? MimeType,long FileSize,string? DocumentType,DateTime UploadedDate);
public sealed class SubmitRequisitionRequest{[StringLength(2000)]public string? Remarks{get;init;}}
