using System.ComponentModel.DataAnnotations;
namespace JamunaBank.Procurement.API.DTOs;
public sealed class AddAttachmentMetadataRequest{[Required,StringLength(30)]public string EntityType{get;init;}=string.Empty;public long EntityId{get;init;}[Required,StringLength(255)]public string FileName{get;init;}=string.Empty;[Required,StringLength(255)]public string OriginalFileName{get;init;}=string.Empty;[Required,StringLength(1000)]public string StorageKey{get;init;}=string.Empty;[StringLength(20)]public string? FileExtension{get;init;}[StringLength(150)]public string? MimeType{get;init;}public long FileSize{get;init;}[StringLength(50)]public string? DocumentType{get;init;}}
public sealed record AttachmentMetadataDto(long Id,string EntityType,long EntityId,string FileName,string OriginalFileName,string StorageKey,string? FileExtension,string? MimeType,long FileSize,string? DocumentType,string UploadedByEmployeeId,DateTime UploadedDate);
public sealed class AddCommentRequest{public long RequisitionId{get;init;}public long? RequisitionItemId{get;init;}[Required,StringLength(30)]public string CommentType{get;init;}="GENERAL";[Required,StringLength(4000)]public string CommentText{get;init;}=string.Empty;}
public sealed record CommentDto(long Id,long RequisitionId,long? RequisitionItemId,string CommentType,string CommentText,string CreatedByEmployeeId,DateTime CreatedDate);
public sealed record ApprovalHistoryDto(long Id,long RequisitionId,long? RequisitionItemId,string ActionType,string ActionByEmployeeId,string ActionRole,string? FromStage,string? ToStage,DateTime ActionDate,string? Remarks,Guid? BatchReferenceId);
public sealed record WorkflowHistoryDto(long Id,long RequisitionId,long? WorkflowRuleId,string? FromStage,string ToStage,string ActionType,string ActionByEmployeeId,DateTime ActionDate,string? Remarks,Guid? BatchReferenceId);
public sealed record SupportingProcurementStatusHistoryDto(long Id,long RequisitionId,string StatusCode,string StatusName,DateTime StatusDate,string? ReferenceNo,string ChangedByEmployeeId,string? Remarks,Guid? BatchReferenceId);
public sealed record AuditLogDto(long Id,string EntityName,long? EntityId,string ActionType,string? OldValueJson,string? NewValueJson,string? ActionByEmployeeId,DateTime ActionDate,string? IpAddress,Guid? CorrelationId);
