using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize,Route("api")]
public sealed class AssetSpecificationController(IAssetSpecificationService service):ControllerBase
{
 [HttpGet("assets/{assetId:long}/specifications")] public async Task<ActionResult<ApiResponse<AssetSpecificationSetDto>>> Get(long assetId,CancellationToken ct){var x=await service.GetAsync(assetId,ct);return Ok(ApiResponse<AssetSpecificationSetDto>.Ok(x,"Asset specifications loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("assets/{assetId:long}/specifications"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Create(long assetId,SaveAssetSpecificationRequest request,CancellationToken ct)=>Map(await service.CreateAsync(assetId,request,ct));
 [HttpPut("asset-specifications/{specId:long}"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Update(long specId,SaveAssetSpecificationRequest request,CancellationToken ct)=>Map(await service.UpdateAsync(specId,request,ct));
 [HttpPost("asset-specifications/{specId:long}/options"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> CreateOption(long specId,CreateAssetSpecificationOptionRequest request,CancellationToken ct)=>Map(await service.CreateOptionAsync(specId,request,ct));
 [HttpPut("asset-specifications/{specId:long}/options"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<IReadOnlyList<StoredProcedureResult?>>>> UpdateOptions(long specId,IReadOnlyList<UpdateAssetSpecificationOptionRequest> requests,CancellationToken ct){var x=await service.UpdateOptionsAsync(specId,requests,ct);return x.Any(r=>r?.ResultCode!=ResultCodes.Success)?BadRequest(ApiResponse<IReadOnlyList<StoredProcedureResult?>>.Fail("One or more options could not be updated.",x.Where(r=>r?.ResultCode!=ResultCodes.Success).Select(r=>r?.ResultMessage??"No result."),HttpContext.TraceIdentifier)):Ok(ApiResponse<IReadOnlyList<StoredProcedureResult?>>.Ok(x,"Options updated.",HttpContext.TraceIdentifier));}
 private ActionResult<ApiResponse<StoredProcedureResult>> Map(StoredProcedureResult? r){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,"Operation completed.",HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Specification data was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Duplicate specification data.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Specification operation failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
