using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize(Policy=AuthorizationPolicyNames.Admin),Route("api/concern-divisions")]
public sealed class ConcernDivisionSetupController(IConcernDivisionSetupService service):ControllerBase
{
 [HttpGet] public async Task<ActionResult<ApiResponse<IReadOnlyList<ConcernDivisionDto>>>> Get([FromQuery]bool activeOnly=true,CancellationToken ct=default){var x=await service.GetDivisionsAsync(activeOnly,ct);return Ok(ApiResponse<IReadOnlyList<ConcernDivisionDto>>.Ok(x,"Concern divisions loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{divisionId:long}/officials")] public async Task<ActionResult<ApiResponse<IReadOnlyList<ConcernOfficialDto>>>> Officials(long divisionId,[FromQuery]bool activeOnly=true,CancellationToken ct=default){var x=await service.GetOfficialsAsync(divisionId,activeOnly,ct);return Ok(ApiResponse<IReadOnlyList<ConcernOfficialDto>>.Ok(x,"Concern officials loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{divisionId:long}/authorities")] public async Task<ActionResult<ApiResponse<IReadOnlyList<ConcernAuthorityDto>>>> Authorities(long divisionId,[FromQuery]bool activeOnly=true,CancellationToken ct=default){var x=await service.GetAuthoritiesAsync(divisionId,activeOnly,ct);return Ok(ApiResponse<IReadOnlyList<ConcernAuthorityDto>>.Ok(x,"Concern authorities loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("{divisionId:long}/officials"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> AddOfficial(long divisionId,AddConcernOfficialRequest request,CancellationToken ct)=>Map(await service.AddOfficialAsync(divisionId,request,ct),"Concern official added.");
 [HttpDelete("officials/{mappingId:long}"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> RemoveOfficial(long mappingId,CancellationToken ct)=>Map(await service.DeactivateOfficialAsync(mappingId,ct),"Concern official deactivated.");
 [HttpPost("{divisionId:long}/authorities"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> AddAuthority(long divisionId,AddConcernAuthorityRequest request,CancellationToken ct)=>Map(await service.AddAuthorityAsync(divisionId,request,ct),"Concern authority added.");
 [HttpDelete("authorities/{mappingId:long}"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> RemoveAuthority(long mappingId,CancellationToken ct)=>Map(await service.DeactivateAuthorityAsync(mappingId,ct),"Concern authority deactivated.");
 private ActionResult<ApiResponse<StoredProcedureResult>> Map(StoredProcedureResult? r,string message){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,message,HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Active mapping was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Mapping already exists.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Mapping is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Mapping operation failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
