using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize(Policy=AuthorizationPolicyNames.ConcernOfficial),Route("api/concern-division/requisitions")]
public sealed class ConcernDivisionWorkflowController(IConcernDivisionWorkflowService service):ControllerBase{
 [HttpGet("pending")]public async Task<ActionResult<ApiResponse<IReadOnlyList<ConcernDivisionPendingDto>>>>Pending(CancellationToken c){var x=await service.GetPendingAsync(c);return Ok(ApiResponse<IReadOnlyList<ConcernDivisionPendingDto>>.Ok(x,"Pending Concern Division requisitions loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{id:long}")]public async Task<ActionResult<ApiResponse<RequisitionDetailDto>>>Detail(long id,CancellationToken c){var x=await service.GetDetailAsync(id,c);return x is null?NotFound(ApiResponse<RequisitionDetailDto>.Fail("Requisition is not pending with your Concern Division.",["It may already have been processed."],HttpContext.TraceIdentifier)):Ok(ApiResponse<RequisitionDetailDto>.Ok(x,"Concern Division review detail loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{id:long}/context")]public async Task<ActionResult<ApiResponse<ConcernDivisionReviewContextDto>>>Context(long id,CancellationToken c){var x=await service.GetContextAsync(id,c);return x is null?NotFound(ApiResponse<ConcernDivisionReviewContextDto>.Fail("Review context was not found.",["The requisition is not assigned to your division."],HttpContext.TraceIdentifier)):Ok(ApiResponse<ConcernDivisionReviewContextDto>.Ok(x,"Concern Division workflow context loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("{id:long}/verify-complete")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Verify(long id,ConcernDivisionActionRequest r,CancellationToken c)=>Map(await service.VerifyCompleteAsync(id,r.Remarks,c),"Concern verification completed.");[HttpPost("{id:long}/forward-authority")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Forward(long id,ConcernDivisionActionRequest r,CancellationToken c)=>Map(await service.ForwardAuthorityAsync(id,r.Remarks,c),"Forwarded to the configured Division Authority pool.");[HttpPost("{id:long}/return")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Return(long id,ConcernDivisionActionRequest r,CancellationToken c)=>Map(await service.ReturnAsync(id,r.Remarks,c),"Returned for clarification.");[HttpPost("{id:long}/not-recommend")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>NotRecommend(long id,ConcernDivisionActionRequest r,CancellationToken c)=>Map(await service.NotRecommendAsync(id,r.Remarks,c),"Requisition not recommended.");
 private ActionResult<ApiResponse<StoredProcedureResult>>Map(StoredProcedureResult?r,string m){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,m,HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Concern Official action is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Requisition was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.InvalidActor=>Forbid(),ResultCodes.InvalidWorkflowState or ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Action is not allowed.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Concern Official action failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}}
