using JamunaBank.Procurement.API.Constants;
using JamunaBank.Procurement.API.DTOs;
using JamunaBank.Procurement.API.Models;
using JamunaBank.Procurement.API.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize(Policy=AuthorizationPolicyNames.ConcernAuthority),Route("api/concern-authority/requisitions")]
public sealed class ConcernAuthorityController(IConcernAuthorityService service):ControllerBase
{
 [HttpGet("pending")]public async Task<ActionResult<ApiResponse<IReadOnlyList<ConcernAuthorityPendingDto>>>> Pending(CancellationToken c){var x=await service.GetPendingAsync(c);return Ok(ApiResponse<IReadOnlyList<ConcernAuthorityPendingDto>>.Ok(x,"Pending Concern Authority requisitions loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{id:long}")]public async Task<ActionResult<ApiResponse<RequisitionDetailDto>>> Detail(long id,CancellationToken c){var x=await service.GetDetailAsync(id,c);return x is null?NotFound(ApiResponse<RequisitionDetailDto>.Fail("Request is not pending in your Division Authority pool.",["Only explicitly forwarded requests are visible."],HttpContext.TraceIdentifier)):Ok(ApiResponse<RequisitionDetailDto>.Ok(x,"Division Authority detail loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{id:long}/context")]public async Task<ActionResult<ApiResponse<ConcernAuthorityReviewContextDto>>> Context(long id,CancellationToken c){var x=await service.GetContextAsync(id,c);return x is null?NotFound(ApiResponse<ConcernAuthorityReviewContextDto>.Fail("Authority context was not found.",["The request may already have been processed."],HttpContext.TraceIdentifier)):Ok(ApiResponse<ConcernAuthorityReviewContextDto>.Ok(x,"Division Authority context loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("{id:long}/approve")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Approve(long id,ConcernAuthorityActionRequest r,CancellationToken c)=>Map(await service.ApproveAsync(id,r.Remarks,c),"Requisition approved.");
 [HttpPost("{id:long}/return")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Return(long id,ConcernAuthorityActionRequest r,CancellationToken c)=>Map(await service.ReturnAsync(id,r.Remarks,c),"Requisition returned.");
 [HttpPost("{id:long}/reject")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Reject(long id,ConcernAuthorityActionRequest r,CancellationToken c)=>Map(await service.RejectAsync(id,r.Remarks,c),"Requisition rejected.");
 [HttpPost("bulk-approve")]public async Task<ActionResult<ApiResponse<ConcernAuthorityBulkResult>>> BulkApprove(ConcernAuthorityBulkApproveRequest r,CancellationToken c){var x=await service.BulkApproveAsync(r,c);return Ok(ApiResponse<ConcernAuthorityBulkResult>.Ok(x,"Bulk approval completed.",HttpContext.TraceIdentifier));}
 [HttpPost("bulk-reject")]public async Task<ActionResult<ApiResponse<ConcernAuthorityBulkResult>>> BulkReject(ConcernAuthorityBulkApproveRequest r,CancellationToken c){var x=await service.BulkRejectAsync(r,c);return Ok(ApiResponse<ConcernAuthorityBulkResult>.Ok(x,"Bulk rejection completed.",HttpContext.TraceIdentifier));}
 private ActionResult<ApiResponse<StoredProcedureResult>> Map(StoredProcedureResult?r,string m){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No result returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,m,HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Concern Authority action is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Requisition was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.InvalidActor=>Forbid(),ResultCodes.InvalidWorkflowState or ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Action is not allowed.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Concern Authority action failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
