using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize(Policy=AuthorizationPolicyNames.Manager),Route("api/manager/requisitions")]
public sealed class ManagerWorkflowController(IManagerWorkflowService service):ControllerBase
{
 [HttpGet("pending")]public async Task<ActionResult<ApiResponse<IReadOnlyList<ManagerPendingRequisitionDto>>>>Pending(CancellationToken ct){var x=await service.GetPendingAsync(ct);return Ok(ApiResponse<IReadOnlyList<ManagerPendingRequisitionDto>>.Ok(x,"Pending Manager requisitions loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{id:long}")]public async Task<ActionResult<ApiResponse<RequisitionDetailDto>>>Detail(long id,CancellationToken ct){var x=await service.GetDetailAsync(id,ct);return x is null?NotFound(ApiResponse<RequisitionDetailDto>.Fail("Requisition was not found.",["The requisition is outside the Manager's organizational authority or does not exist."],HttpContext.TraceIdentifier)):Ok(ApiResponse<RequisitionDetailDto>.Ok(x,"Manager requisition detail loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("{id:long}/approve")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Approve(long id,ManagerActionRequest request,CancellationToken ct)=>Map(await service.ApproveAsync(id,request.Remarks,ct),"Requisition approved and routed to the Procurement Officer queue.");
 [HttpPost("{id:long}/return")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Return(long id,ManagerActionRequest request,CancellationToken ct)=>Map(await service.ReturnAsync(id,request.Remarks,ct),"Requisition returned to the Maker.");
 [HttpPost("{id:long}/reject")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Reject(long id,ManagerActionRequest request,CancellationToken ct)=>Map(await service.RejectAsync(id,request.Remarks,ct),"Requisition rejected.");
 private ActionResult<ApiResponse<StoredProcedureResult>>Map(StoredProcedureResult?r,string message){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,message,HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Manager action is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Requisition was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.InvalidActor=>Forbid(),ResultCodes.InvalidWorkflowState=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Manager action is not allowed in the current state.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Manager action failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
