using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize(Policy=AuthorizationPolicyNames.ProcurementTracker),Route("api/procurement-tracking")]
public sealed class ProcurementTrackingController(IProcurementTrackingService service):ControllerBase
{
 [HttpGet("statuses")]public async Task<ActionResult<ApiResponse<IReadOnlyList<ProcurementStatusDto>>>>Statuses(CancellationToken c){var x=await service.GetStatusesAsync(c);return Ok(ApiResponse<IReadOnlyList<ProcurementStatusDto>>.Ok(x,"Procurement statuses loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("search")]public async Task<ActionResult<ApiResponse<IReadOnlyList<ProcurementTrackingSearchDto>>>>Search([FromQuery]string?requisitionNo,[FromQuery]long?orgUnitId,[FromQuery]long?assetId,[FromQuery]string?statusCode,CancellationToken c){var x=await service.SearchAsync(requisitionNo,orgUnitId,assetId,statusCode,c);return Ok(ApiResponse<IReadOnlyList<ProcurementTrackingSearchDto>>.Ok(x,"Procurement tracking results loaded.",HttpContext.TraceIdentifier));}[HttpGet("{requisitionId:long}")]public async Task<ActionResult<ApiResponse<ProcurementTrackingDetailDto>>>Get(long requisitionId,CancellationToken c){var x=await service.GetAsync(requisitionId,c);return x is null?NotFound(ApiResponse<ProcurementTrackingDetailDto>.Fail("Procurement tracking was not found.",[],HttpContext.TraceIdentifier)):Ok(ApiResponse<ProcurementTrackingDetailDto>.Ok(x,"Procurement tracking loaded.",HttpContext.TraceIdentifier));}[HttpPost("update-status")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Update(ProcurementTrackingUpdateRequest r,CancellationToken c)=>Map(await service.UpdateStatusAsync(r,c));[HttpPost("bulk-update-status")]public async Task<ActionResult<ApiResponse<ProcurementTrackingBulkResult>>>Bulk(ProcurementTrackingUpdateRequest r,CancellationToken c){var x=await service.BulkUpdateStatusAsync(r,c);return Ok(ApiResponse<ProcurementTrackingBulkResult>.Ok(x,"Bulk status update completed.",HttpContext.TraceIdentifier));}
 private ActionResult<ApiResponse<StoredProcedureResult>>Map(StoredProcedureResult?r){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",[],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,"Procurement status updated.",HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Status update is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Tracking or status was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Status update failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
