using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize,Route("api/assets/{assetId:long}/procurement-officers")]
public sealed class ProcurementOfficerAssetMappingController(IProcurementOfficerAssetMappingService service):ControllerBase
{
 [HttpGet] public async Task<ActionResult<ApiResponse<IReadOnlyList<ProcurementOfficerAssetMappingDto>>>> Get(long assetId,[FromQuery]bool activeOnly=true,CancellationToken ct=default){var x=await service.GetByAssetAsync(assetId,activeOnly,ct);return Ok(ApiResponse<IReadOnlyList<ProcurementOfficerAssetMappingDto>>.Ok(x,"Procurement officer mappings loaded.",HttpContext.TraceIdentifier));}
 [HttpPost,Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Add(long assetId,AddProcurementOfficerAssetMappingRequest request,CancellationToken ct)=>Map(await service.AddAsync(assetId,request,ct),"Procurement officer mapping added.");
 [HttpDelete("{mappingId:long}"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Deactivate(long assetId,long mappingId,CancellationToken ct)=>Map(await service.DeactivateAsync(assetId,mappingId,ct),"Procurement officer mapping deactivated.");
 private ActionResult<ApiResponse<StoredProcedureResult>> Map(StoredProcedureResult? r,string message){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,message,HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Active mapping was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Mapping conflicts with an existing assignment.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Mapping operation failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
