using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize(Policy=AuthorizationPolicyNames.ProcurementOfficer),Route("api/procurement-officer/requisitions")]
public sealed class ProcurementOfficerWorkflowController(IProcurementOfficerWorkflowService service):ControllerBase
{
 [HttpGet]public async Task<ActionResult<ApiResponse<IReadOnlyList<ProcurementOfficerRequisitionDto>>>>Get(CancellationToken c){var x=await service.GetAssignedAsync(c);return Ok(ApiResponse<IReadOnlyList<ProcurementOfficerRequisitionDto>>.Ok(x,"Procurement Officer requisitions loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{id:long}")]public async Task<ActionResult<ApiResponse<RequisitionDetailDto>>>Detail(long id,CancellationToken c){var x=await service.GetDetailAsync(id,c);return x is null?NotFound(ApiResponse<RequisitionDetailDto>.Fail("Requisition was not found.",["The requisition is not visible to this Procurement Officer."],HttpContext.TraceIdentifier)):Ok(ApiResponse<RequisitionDetailDto>.Ok(x,"Procurement Officer requisition detail loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("{id:long}/take")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Take(long id,ProcurementOfficerActionRequest r,CancellationToken c)=>Map(await service.TakeAsync(id,r.Remarks,c),"Requisition taken for review.");
 [HttpPost("{id:long}/approve")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Approve(long id,ProcurementOfficerActionRequest r,CancellationToken c)=>Map(await service.ApproveAsync(id,r.Remarks,c),"Requisition approved and routed by workflow configuration.");
 [HttpPost("{id:long}/return")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Return(long id,ProcurementOfficerActionRequest r,CancellationToken c)=>Map(await service.ReturnAsync(id,r.Remarks,c),"Requisition returned.");
 [HttpPost("{id:long}/reject")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Reject(long id,ProcurementOfficerActionRequest r,CancellationToken c)=>Map(await service.RejectAsync(id,r.Remarks,c),"Requisition rejected.");
 [HttpPost("{id:long}/comments")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Comment(long id,ProcurementOfficerCommentRequest r,CancellationToken c)=>Map(await service.AddCommentAsync(id,r,c),"Comment added.");
 private ActionResult<ApiResponse<StoredProcedureResult>>Map(StoredProcedureResult?r,string m){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,m,HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Procurement Officer action is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Requisition was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.InvalidActor=>Forbid(),ResultCodes.InvalidWorkflowState or ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Action is not allowed.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Procurement Officer action failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
