using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize(Policy=AuthorizationPolicyNames.ProcurementAuthority),Route("api/procurement-authority/requisitions")]
public sealed class ProcurementAuthorityController(IProcurementAuthorityService service):ControllerBase{
 [HttpGet("pending")]public async Task<ActionResult<ApiResponse<IReadOnlyList<ProcurementAuthorityPendingDto>>>>Pending(CancellationToken c){var x=await service.GetPendingAsync(c);return Ok(ApiResponse<IReadOnlyList<ProcurementAuthorityPendingDto>>.Ok(x,"Pending Procurement Authority requisitions loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{id:long}")]public async Task<ActionResult<ApiResponse<RequisitionDetailDto>>>Detail(long id,CancellationToken c){var x=await service.GetDetailAsync(id,c);return x is null?NotFound(ApiResponse<RequisitionDetailDto>.Fail("Requisition is no longer pending.",["Another authority may already have acted."],HttpContext.TraceIdentifier)):Ok(ApiResponse<RequisitionDetailDto>.Ok(x,"Authority review detail loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("{id:long}/context")]public async Task<ActionResult<ApiResponse<ProcurementAuthorityReviewContextDto>>>Context(long id,CancellationToken c){var x=await service.GetContextAsync(id,c);return x is null?NotFound(ApiResponse<ProcurementAuthorityReviewContextDto>.Fail("Review context was not found.",["The request is not in your shared approval pool."],HttpContext.TraceIdentifier)):Ok(ApiResponse<ProcurementAuthorityReviewContextDto>.Ok(x,"Authority review context loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("{id:long}/approve")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Approve(long id,ProcurementAuthorityActionRequest r,CancellationToken c)=>Map(await service.ApproveAsync(id,r.Remarks,c),"Requisition approved.");[HttpPost("{id:long}/reject")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Reject(long id,ProcurementAuthorityActionRequest r,CancellationToken c)=>Map(await service.RejectAsync(id,r.Remarks,c),"Requisition rejected.");[HttpPost("{id:long}/forward")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Forward(long id,ProcurementAuthorityActionRequest r,CancellationToken c)=>Map(await service.ForwardAsync(id,r.Remarks,c),"Requisition forwarded.");[HttpPost("bulk-approve")]public async Task<ActionResult<ApiResponse<ProcurementAuthorityBulkResult>>>Bulk(ProcurementAuthorityBulkApproveRequest r,CancellationToken c){var x=await service.BulkApproveAsync(r,c);return Ok(ApiResponse<ProcurementAuthorityBulkResult>.Ok(x,"Bulk approval completed.",HttpContext.TraceIdentifier));}
 private ActionResult<ApiResponse<StoredProcedureResult>>Map(StoredProcedureResult?r,string m){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No result returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,m,HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Authority action is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Requisition was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.InvalidActor=>Forbid(),ResultCodes.InvalidWorkflowState or ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Action is not allowed.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Authority action failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}}
