using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize(Policy=AuthorizationPolicyNames.Maker),Route("api/requisitions")]
public sealed class RequisitionMakerController(IRequisitionMakerService service):ControllerBase
{
 [HttpPost]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Create(SaveRequisitionRequest request,CancellationToken ct)=>Map(await service.CreateAsync(request,ct),"Requisition draft created.");
 [HttpPut("{id:long}")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Update(long id,SaveRequisitionRequest request,CancellationToken ct)=>Map(await service.UpdateAsync(id,request,ct),"Requisition draft updated.");
 [HttpGet("{id:long}")]public async Task<ActionResult<ApiResponse<RequisitionDetailDto>>>Get(long id,CancellationToken ct){var x=await service.GetAsync(id,ct);return x is null?NotFound(ApiResponse<RequisitionDetailDto>.Fail("Requisition was not found.",["No requisition belonging to the authenticated maker has this ID."],HttpContext.TraceIdentifier)):Ok(ApiResponse<RequisitionDetailDto>.Ok(x,"Requisition loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("my")]public async Task<ActionResult<ApiResponse<IReadOnlyList<RequisitionSummaryDto>>>>Mine(CancellationToken ct){var x=await service.GetMineAsync(ct);return Ok(ApiResponse<IReadOnlyList<RequisitionSummaryDto>>.Ok(x,"Maker requisitions loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("{id:long}/submit")]public async Task<ActionResult<ApiResponse<StoredProcedureResult>>>Submit(long id,SubmitRequisitionRequest request,CancellationToken ct)=>Map(await service.SubmitAsync(id,request.Remarks,ct),"Requisition submitted.");
 private ActionResult<ApiResponse<StoredProcedureResult>>Map(StoredProcedureResult?r,string message){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,message,HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Requisition is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Requisition was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.InvalidActor=>Forbid(),ResultCodes.InvalidWorkflowState=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Requisition cannot be submitted in its current state.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Requisition conflicts with existing data.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Requisition operation failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
