using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Services.Interfaces;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace JamunaBank.Procurement.API.Controllers;
[ApiController,Authorize,Route("api")]
public sealed class WorkflowRuleController(IWorkflowRuleService service):ControllerBase
{
 [HttpGet("workflow-rules")] public async Task<ActionResult<ApiResponse<IReadOnlyList<WorkflowRuleDto>>>> Get([FromQuery]bool activeOnly=true,CancellationToken ct=default){var x=await service.GetAllAsync(activeOnly,ct);return Ok(ApiResponse<IReadOnlyList<WorkflowRuleDto>>.Ok(x,"Workflow rules loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("workflow-rules/{id:long}")] public async Task<ActionResult<ApiResponse<WorkflowRuleDto>>> GetById(long id,CancellationToken ct){var x=await service.GetByIdAsync(id,ct);return x is null?NotFound(ApiResponse<WorkflowRuleDto>.Fail("Workflow rule was not found.",["No rule has the specified ID."],HttpContext.TraceIdentifier)):Ok(ApiResponse<WorkflowRuleDto>.Ok(x,"Workflow rule loaded.",HttpContext.TraceIdentifier));}
 [HttpGet("assets/{assetId:long}/workflow-rules")] public async Task<ActionResult<ApiResponse<IReadOnlyList<WorkflowRuleDto>>>> GetByAsset(long assetId,[FromQuery]bool activeOnly=true,CancellationToken ct=default){var x=await service.GetByAssetAsync(assetId,activeOnly,ct);return Ok(ApiResponse<IReadOnlyList<WorkflowRuleDto>>.Ok(x,"Asset workflow rules loaded.",HttpContext.TraceIdentifier));}
 [HttpPost("workflow-rules"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Create(SaveWorkflowRuleRequest request,CancellationToken ct)=>Map(await service.CreateAsync(request,ct),"Workflow rule created.");
 [HttpPut("workflow-rules/{id:long}"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> Update(long id,SaveWorkflowRuleRequest request,CancellationToken ct)=>Map(await service.UpdateAsync(id,request,ct),"Workflow rule updated.");
 [HttpPut("workflow-rules/{id:long}/activation"),Authorize(Policy=AuthorizationPolicyNames.Admin)] public async Task<ActionResult<ApiResponse<StoredProcedureResult>>> SetActive(long id,SetActiveRequest request,CancellationToken ct)=>Map(await service.SetActiveAsync(id,request.IsActive,ct),request.IsActive?"Workflow rule activated.":"Workflow rule deactivated.");
 [HttpPost("workflow-rules/evaluate")] public async Task<ActionResult<ApiResponse<WorkflowEvaluationDto>>> Evaluate(EvaluateWorkflowRuleRequest request,CancellationToken ct){var x=await service.EvaluateAsync(request,ct);return x is null?NotFound(ApiResponse<WorkflowEvaluationDto>.Fail("No matching workflow rule was found.",["Review active rules, amount ranges, and effective dates."],HttpContext.TraceIdentifier)):Ok(ApiResponse<WorkflowEvaluationDto>.Ok(x,"Workflow rule evaluated by the database.",HttpContext.TraceIdentifier));}
 private ActionResult<ApiResponse<StoredProcedureResult>> Map(StoredProcedureResult? r,string message){if(r is null)return StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("No stored-procedure result was returned.",["Operation failed."],HttpContext.TraceIdentifier));return r.ResultCode switch{ResultCodes.Success=>Ok(ApiResponse<StoredProcedureResult>.Ok(r,message,HttpContext.TraceIdentifier)),ResultCodes.NotFound=>NotFound(ApiResponse<StoredProcedureResult>.Fail("Workflow rule was not found.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.Conflict=>Conflict(ApiResponse<StoredProcedureResult>.Fail("Workflow rule conflicts with an existing active rule.",[r.ResultMessage],HttpContext.TraceIdentifier)),ResultCodes.ValidationError=>BadRequest(ApiResponse<StoredProcedureResult>.Fail("Workflow rule is invalid.",[r.ResultMessage],HttpContext.TraceIdentifier)),_=>StatusCode(500,ApiResponse<StoredProcedureResult>.Fail("Workflow rule operation failed.",[r.ResultMessage],HttpContext.TraceIdentifier))};}
}
