using JamunaBank.Procurement.API.Constants;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Services.Implementations;
public sealed class ProcurementTrackingService(IProcurementTrackingRepository repository,ICurrentUserService currentUser):IProcurementTrackingService
{
 public Task<IReadOnlyList<ProcurementStatusDto>>GetStatusesAsync(CancellationToken c)=>repository.GetStatusesAsync(c);
 public Task<IReadOnlyList<ProcurementTrackingSearchDto>>SearchAsync(string?n,long?o,long?a,string?s,CancellationToken c){if(o<=0||a<=0)throw new ArgumentException("Filter IDs must be positive.");return repository.SearchAsync(N(n),o,a,N(s)?.ToUpperInvariant(),c);}public Task<ProcurementTrackingDetailDto?>GetAsync(long id,CancellationToken c)=>repository.GetAsync(Valid(id),c);
 public Task<StoredProcedureResult?>UpdateStatusAsync(ProcurementTrackingUpdateRequest r,CancellationToken c){Validate(r);if(r.RequisitionIds.Count!=1)throw new ArgumentException("Single status update requires exactly one requisition ID.");return repository.UpdateStatusAsync(r.RequisitionIds.Single(),Code(r),r.StatusDate,r.ReferenceNo?.Trim(),r.Remarks?.Trim(),currentUser.EmployeeId,null,c);}
 public async Task<ProcurementTrackingBulkResult>BulkUpdateStatusAsync(ProcurementTrackingUpdateRequest r,CancellationToken c){Validate(r);var ids=r.RequisitionIds.Distinct().ToArray();var known=(await repository.SearchAsync(null,null,null,null,c)).ToDictionary(x=>x.RequisitionId,x=>x.RequisitionNo);var batch=Guid.NewGuid();var results=new List<ProcurementTrackingUpdateItemResult>(ids.Length);foreach(var id in ids){StoredProcedureResult?x;try{x=await repository.UpdateStatusAsync(id,Code(r),r.StatusDate,r.ReferenceNo?.Trim(),r.Remarks?.Trim(),currentUser.EmployeeId,batch,c);}catch(OperationCanceledException){throw;}catch(Exception){x=new(ResultCodes.UnexpectedError,"The requisition could not be processed.",id,null);}x??=new(ResultCodes.UnexpectedError,"No stored-procedure result was returned.",id,null);known.TryGetValue(id,out var no);results.Add(new(id,no,x.ResultCode,x.ResultMessage,x.ResultCode==ResultCodes.Success?Code(r):null));}var ok=results.Count(x=>x.ResultCode==ResultCodes.Success);return new(batch,ids.Length,ok,ids.Length-ok,results);}
 private static void Validate(ProcurementTrackingUpdateRequest r){if(r.RequisitionIds is null||r.RequisitionIds.Count==0||r.RequisitionIds.Any(x=>x<=0))throw new ArgumentException("Positive requisition IDs are required.");_ = Code(r);if(r.StatusDate==default)throw new ArgumentException("Status date is required.");if(r.StatusDate.ToUniversalTime()>DateTime.UtcNow.AddMinutes(5))throw new ArgumentException("Status date cannot be in the future.");}private static string Code(ProcurementTrackingUpdateRequest r){var x=N(r.NewStatusCode)?.ToUpperInvariant();if(x is null||x.Length>40)throw new ArgumentException("A valid status code is required.");return x;}private static long Valid(long id){if(id<=0)throw new ArgumentOutOfRangeException(nameof(id));return id;}private static string?N(string?x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
}
