using System.Data;using JamunaBank.Procurement.API.Data;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Base;using JamunaBank.Procurement.API.Repositories.Interfaces;
namespace JamunaBank.Procurement.API.Repositories.Implementations;
public sealed class AssetSpecificationRepository(IStoredProcedureExecutor p):BaseRepository(p),IAssetSpecificationRepository
{
 public async Task<AssetSpecificationSetDto> GetByAssetAsync(long assetId,CancellationToken ct)
 {
  var rows=await StoredProcedures.QueryAsync("dbo.usp_AssetSpec_GetByAsset",r=>new Row(r.GetInt64(r.GetOrdinal("ASSET_SPEC_ID")),r.GetString(r.GetOrdinal("SPEC_NAME")),r.GetString(r.GetOrdinal("SPEC_TYPE")),r.GetBoolean(r.GetOrdinal("IS_MANDATORY")),r.GetInt32(r.GetOrdinal("DISPLAY_ORDER")),r.GetBoolean(r.GetOrdinal("IS_ACTIVE")),r.GetNullable<long>("ASSET_SPEC_OPTION_ID"),r.GetNullableString("OPTION_VALUE"),r.GetNullable<int>("OPTION_DISPLAY_ORDER"),r.GetNullable<bool>("OPTION_IS_ACTIVE")),[SqlParameterFactory.Input("@AssetId",SqlDbType.BigInt,assetId)],ct);
  var specs=rows.GroupBy(x=>new{x.Id,x.Name,x.Type,x.Mandatory,x.Order,x.Active}).Select(g=>new AssetSpecificationDto(g.Key.Id,g.Key.Name,g.Key.Type,g.Key.Mandatory,g.Key.Order,g.Key.Active,g.Where(x=>x.OptionId.HasValue).Select(x=>new AssetSpecificationOptionDto(x.OptionId!.Value,x.OptionValue!,x.OptionOrder!.Value,x.OptionActive!.Value)).ToArray())).ToArray();
  return new(assetId,specs);
 }
 public Task<StoredProcedureResult?> CreateAsync(long id,SaveAssetSpecificationRequest x,string a,CancellationToken ct)=>Run("dbo.usp_AssetSpec_Create",[I("@AssetId",SqlDbType.BigInt,id),I("@SpecName",SqlDbType.NVarChar,x.Name.Trim(),150),I("@SpecType",SqlDbType.VarChar,x.Type.Trim().ToUpperInvariant(),20),I("@IsMandatory",SqlDbType.Bit,x.IsMandatory),I("@DisplayOrder",SqlDbType.Int,x.DisplayOrder),I("@IsActive",SqlDbType.Bit,x.IsActive),I("@Actor",SqlDbType.VarChar,a,50)],ct);
 public Task<StoredProcedureResult?> UpdateAsync(long id,SaveAssetSpecificationRequest x,string a,CancellationToken ct)=>Run("dbo.usp_AssetSpec_Update",[I("@SpecId",SqlDbType.BigInt,id),I("@SpecName",SqlDbType.NVarChar,x.Name.Trim(),150),I("@SpecType",SqlDbType.VarChar,x.Type.Trim().ToUpperInvariant(),20),I("@IsMandatory",SqlDbType.Bit,x.IsMandatory),I("@DisplayOrder",SqlDbType.Int,x.DisplayOrder),I("@IsActive",SqlDbType.Bit,x.IsActive),I("@Actor",SqlDbType.VarChar,a,50)],ct);
 public Task<StoredProcedureResult?> CreateOptionAsync(long id,CreateAssetSpecificationOptionRequest x,string a,CancellationToken ct)=>Run("dbo.usp_AssetSpecOption_Create",[I("@SpecId",SqlDbType.BigInt,id),I("@OptionValue",SqlDbType.NVarChar,x.Value.Trim(),300),I("@DisplayOrder",SqlDbType.Int,x.DisplayOrder),I("@IsActive",SqlDbType.Bit,x.IsActive),I("@Actor",SqlDbType.VarChar,a,50)],ct);
 public Task<StoredProcedureResult?> UpdateOptionAsync(long specId,UpdateAssetSpecificationOptionRequest x,string a,CancellationToken ct)=>Run("dbo.usp_AssetSpecOption_Update",[I("@SpecId",SqlDbType.BigInt,specId),I("@OptionId",SqlDbType.BigInt,x.OptionId),I("@OptionValue",SqlDbType.NVarChar,x.Value.Trim(),300),I("@DisplayOrder",SqlDbType.Int,x.DisplayOrder),I("@IsActive",SqlDbType.Bit,x.IsActive),I("@Actor",SqlDbType.VarChar,a,50)],ct);
 private Task<StoredProcedureResult?> Run(string n,IEnumerable<Microsoft.Data.SqlClient.SqlParameter> ps,CancellationToken ct)=>StoredProcedures.QuerySingleOrDefaultAsync(n,StoredProcedureResult.FromReader,ps,ct);
 private static Microsoft.Data.SqlClient.SqlParameter I(string n,SqlDbType t,object? v,int? s=null)=>SqlParameterFactory.Input(n,t,v,s);
 private sealed record Row(long Id,string Name,string Type,bool Mandatory,int Order,bool Active,long? OptionId,string? OptionValue,int? OptionOrder,bool? OptionActive);
}
