using System.Data;using JamunaBank.Procurement.API.Data;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Base;using JamunaBank.Procurement.API.Repositories.Interfaces;using Microsoft.Data.SqlClient;
namespace JamunaBank.Procurement.API.Repositories.Implementations;
public sealed class ManagerWorkflowRepository(IStoredProcedureExecutor p):BaseRepository(p),IManagerWorkflowRepository
{
 public Task<IReadOnlyList<ManagerPendingRequisitionDto>>GetPendingAsync(string e,CancellationToken c)=>StoredProcedures.QueryAsync("dbo.usp_Manager_GetPending",r=>new ManagerPendingRequisitionDto(r.GetInt64(r.GetOrdinal("REQUISITION_ID")),r.GetString(r.GetOrdinal("REQUISITION_NO")),r.GetDateTime(r.GetOrdinal("REQUESTED_DATE")),r.GetString(r.GetOrdinal("JUSTIFICATION")),r.GetDecimal(r.GetOrdinal("TOTAL_ESTIMATED_AMOUNT")),r.GetInt64(r.GetOrdinal("REQUESTED_ORG_UNIT_ID")),r.GetString(r.GetOrdinal("REQUESTED_BY_EMPLOYEE_ID")),r.GetString(r.GetOrdinal("REQUESTED_BY_NAME")),r.GetString(r.GetOrdinal("CURRENT_STATUS")),r.GetInt32(r.GetOrdinal("ITEM_COUNT"))),[I("@EmployeeId",SqlDbType.VarChar,e,30)],c);
 public async Task<RequisitionDetailDto?>GetDetailAsync(long id,string e,CancellationToken c)=>RequisitionDetailDataSetMapper.Map(await StoredProcedures.QueryDataSetAsync("dbo.usp_Manager_GetRequisitionDetail",[I("@RequisitionId",SqlDbType.BigInt,id),I("@EmployeeId",SqlDbType.VarChar,e,30)],c));
 public Task<StoredProcedureResult?>ApproveAsync(long id,string e,string?m,CancellationToken c)=>Run("dbo.usp_Manager_Approve",id,e,m,c);public Task<StoredProcedureResult?>ReturnAsync(long id,string e,string m,CancellationToken c)=>Run("dbo.usp_Manager_Return",id,e,m,c);public Task<StoredProcedureResult?>RejectAsync(long id,string e,string m,CancellationToken c)=>Run("dbo.usp_Manager_Reject",id,e,m,c);
 private Task<StoredProcedureResult?>Run(string n,long id,string e,string?m,CancellationToken c)=>StoredProcedures.QuerySingleOrDefaultAsync(n,StoredProcedureResult.FromReader,[I("@RequisitionId",SqlDbType.BigInt,id),I("@ActorEmployeeId",SqlDbType.VarChar,e,30),I("@Remarks",SqlDbType.NVarChar,m,2000),I("@BatchReferenceId",SqlDbType.UniqueIdentifier,null)],c);private static SqlParameter I(string n,SqlDbType t,object?v,int?s=null)=>SqlParameterFactory.Input(n,t,v,s);
}
