using System.Data;using JamunaBank.Procurement.API.Data;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Base;using JamunaBank.Procurement.API.Repositories.Interfaces;using Microsoft.Data.SqlClient;
namespace JamunaBank.Procurement.API.Repositories.Implementations;
public sealed class SupportingRepository(IStoredProcedureExecutor p):BaseRepository(p),ISupportingRepository
{
 public Task<StoredProcedureResult?>AddAttachmentAsync(AddAttachmentMetadataRequest x,string e,CancellationToken c)=>StoredProcedures.QuerySingleOrDefaultAsync("dbo.usp_Attachment_Add",StoredProcedureResult.FromReader,[I("@EntityType",SqlDbType.VarChar,x.EntityType.Trim().ToUpperInvariant(),30),I("@EntityId",SqlDbType.BigInt,x.EntityId),I("@FileName",SqlDbType.NVarChar,x.FileName.Trim(),255),I("@OriginalFileName",SqlDbType.NVarChar,x.OriginalFileName.Trim(),255),I("@StorageKey",SqlDbType.NVarChar,x.StorageKey.Trim(),1000),I("@FileExtension",SqlDbType.VarChar,x.FileExtension?.Trim(),20),I("@MimeType",SqlDbType.VarChar,x.MimeType?.Trim(),150),I("@FileSize",SqlDbType.BigInt,x.FileSize),I("@DocumentType",SqlDbType.VarChar,x.DocumentType?.Trim(),50),I("@ActorEmployeeId",SqlDbType.VarChar,e,30)],c);
 public Task<IReadOnlyList<AttachmentMetadataDto>>GetAttachmentsAsync(string t,long id,CancellationToken c)=>StoredProcedures.QueryAsync<AttachmentMetadataDto>("dbo.usp_Attachment_GetByEntity",r=>new(r.GetInt64(r.GetOrdinal("ATTACHMENT_ID")),r.GetString(r.GetOrdinal("ENTITY_TYPE")),r.GetInt64(r.GetOrdinal("ENTITY_ID")),r.GetString(r.GetOrdinal("FILE_NAME")),r.GetString(r.GetOrdinal("ORIGINAL_FILE_NAME")),r.GetString(r.GetOrdinal("FILE_PATH_OR_STORAGE_KEY")),r.GetNullableString("FILE_EXTENSION"),r.GetNullableString("MIME_TYPE"),r.GetInt64(r.GetOrdinal("FILE_SIZE")),r.GetNullableString("DOCUMENT_TYPE"),r.GetString(r.GetOrdinal("UPLOADED_BY_EMPLOYEE_ID")),r.GetDateTime(r.GetOrdinal("UPLOADED_DATE"))),[I("@EntityType",SqlDbType.VarChar,t,30),I("@EntityId",SqlDbType.BigInt,id),I("@ActiveOnly",SqlDbType.Bit,true)],c);
 public Task<StoredProcedureResult?>AddCommentAsync(AddCommentRequest x,string e,CancellationToken c)=>StoredProcedures.QuerySingleOrDefaultAsync("dbo.usp_Comment_Add",StoredProcedureResult.FromReader,[I("@RequisitionId",SqlDbType.BigInt,x.RequisitionId),I("@ReqItemId",SqlDbType.BigInt,x.RequisitionItemId),I("@CommentType",SqlDbType.VarChar,x.CommentType.Trim().ToUpperInvariant(),30),I("@CommentText",SqlDbType.NVarChar,x.CommentText.Trim(),4000),I("@ActorEmployeeId",SqlDbType.VarChar,e,30)],c);
 public Task<IReadOnlyList<CommentDto>>GetCommentsAsync(long id,CancellationToken c)=>StoredProcedures.QueryAsync<CommentDto>("dbo.usp_Comment_GetByRequisition",r=>new(r.GetInt64(r.GetOrdinal("COMMENT_ID")),r.GetInt64(r.GetOrdinal("REQUISITION_ID")),r.GetNullable<long>("REQ_ITEM_ID"),r.GetString(r.GetOrdinal("COMMENT_TYPE")),r.GetString(r.GetOrdinal("COMMENT_TEXT")),r.GetString(r.GetOrdinal("CREATED_BY_EMPLOYEE_ID")),r.GetDateTime(r.GetOrdinal("CREATED_DATE"))),[I("@RequisitionId",SqlDbType.BigInt,id),I("@ActiveOnly",SqlDbType.Bit,true)],c);
 public Task<IReadOnlyList<ApprovalHistoryDto>>GetApprovalHistoryAsync(long id,CancellationToken c)=>StoredProcedures.QueryAsync<ApprovalHistoryDto>("dbo.usp_History_GetApproval",r=>new(r.GetInt64(r.GetOrdinal("APPROVAL_ID")),r.GetInt64(r.GetOrdinal("REQUISITION_ID")),r.GetNullable<long>("REQ_ITEM_ID"),r.GetString(r.GetOrdinal("ACTION_TYPE")),r.GetString(r.GetOrdinal("ACTION_BY_EMPLOYEE_ID")),r.GetString(r.GetOrdinal("ACTION_ROLE")),r.GetNullableString("FROM_STAGE"),r.GetNullableString("TO_STAGE"),r.GetDateTime(r.GetOrdinal("ACTION_DATETIME")),r.GetNullableString("REMARKS"),r.GetNullable<Guid>("BATCH_REFERENCE_ID")),[I("@RequisitionId",SqlDbType.BigInt,id)],c);
 public Task<IReadOnlyList<WorkflowHistoryDto>>GetWorkflowHistoryAsync(long id,CancellationToken c)=>StoredProcedures.QueryAsync<WorkflowHistoryDto>("dbo.usp_History_GetWorkflow",r=>new(r.GetInt64(r.GetOrdinal("WORKFLOW_HISTORY_ID")),r.GetInt64(r.GetOrdinal("REQUISITION_ID")),r.GetNullable<long>("WORKFLOW_RULE_ID"),r.GetNullableString("FROM_STAGE"),r.GetString(r.GetOrdinal("TO_STAGE")),r.GetString(r.GetOrdinal("ACTION_TYPE")),r.GetString(r.GetOrdinal("ACTION_BY_EMPLOYEE_ID")),r.GetDateTime(r.GetOrdinal("ACTION_DATETIME")),r.GetNullableString("REMARKS"),r.GetNullable<Guid>("BATCH_REFERENCE_ID")),[I("@RequisitionId",SqlDbType.BigInt,id)],c);
 public Task<IReadOnlyList<SupportingProcurementStatusHistoryDto>>GetProcurementHistoryAsync(long id,CancellationToken c)=>StoredProcedures.QueryAsync<SupportingProcurementStatusHistoryDto>("dbo.usp_History_GetProcurementStatus",r=>new(r.GetInt64(r.GetOrdinal("STATUS_HISTORY_ID")),r.GetInt64(r.GetOrdinal("REQUISITION_ID")),r.GetString(r.GetOrdinal("STATUS_CODE")),r.GetString(r.GetOrdinal("STATUS_NAME")),r.GetDateTime(r.GetOrdinal("STATUS_DATE")),r.GetNullableString("REFERENCE_NO"),r.GetString(r.GetOrdinal("CHANGED_BY_EMPLOYEE_ID")),r.GetNullableString("REMARKS"),r.GetNullable<Guid>("BATCH_REFERENCE_ID")),[I("@RequisitionId",SqlDbType.BigInt,id)],c);
 public Task<IReadOnlyList<AuditLogDto>>GetAuditAsync(string?n,long?id,int page,int size,CancellationToken c)=>StoredProcedures.QueryAsync<AuditLogDto>("dbo.usp_AuditLog_Search",r=>new(r.GetInt64(r.GetOrdinal("AUDIT_ID")),r.GetString(r.GetOrdinal("ENTITY_NAME")),r.GetNullable<long>("ENTITY_ID"),r.GetString(r.GetOrdinal("ACTION_TYPE")),r.GetNullableString("OLD_VALUE_JSON"),r.GetNullableString("NEW_VALUE_JSON"),r.GetNullableString("ACTION_BY_EMPLOYEE_ID"),r.GetDateTime(r.GetOrdinal("ACTION_DATETIME")),r.GetNullableString("IP_ADDRESS"),r.GetNullable<Guid>("CORRELATION_ID")),[I("@EntityName",SqlDbType.VarChar,n,100),I("@EntityId",SqlDbType.BigInt,id),I("@PageNumber",SqlDbType.Int,page),I("@PageSize",SqlDbType.Int,size)],c);private static SqlParameter I(string n,SqlDbType t,object?v,int?s=null)=>SqlParameterFactory.Input(n,t,v,s);
}
