using System.Data;using JamunaBank.Procurement.API.Data;using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Base;using JamunaBank.Procurement.API.Repositories.Interfaces;using Microsoft.Data.SqlClient;
namespace JamunaBank.Procurement.API.Repositories.Implementations;
public sealed class WorkflowRuleRepository(IStoredProcedureExecutor p):BaseRepository(p),IWorkflowRuleRepository
{
 public Task<IReadOnlyList<WorkflowRuleDto>> GetAllAsync(bool a,CancellationToken c)=>StoredProcedures.QueryAsync("dbo.usp_WorkflowRule_GetAll",MapEnriched,[I("@ActiveOnly",SqlDbType.Bit,a)],c);
 public Task<WorkflowRuleDto?> GetByIdAsync(long id,CancellationToken c)=>StoredProcedures.QuerySingleOrDefaultAsync("dbo.usp_WorkflowRule_GetById",MapEnriched,[I("@WorkflowRuleId",SqlDbType.BigInt,id)],c);
 public Task<IReadOnlyList<WorkflowRuleDto>> GetByAssetAsync(long id,bool a,CancellationToken c)=>StoredProcedures.QueryAsync("dbo.usp_WorkflowRule_GetByAsset",MapBasic,[I("@AssetId",SqlDbType.BigInt,id),I("@ActiveOnly",SqlDbType.Bit,a)],c);
 public Task<StoredProcedureResult?> SaveAsync(long? id,SaveWorkflowRuleRequest x,string actor,CancellationToken c)=>StoredProcedures.QuerySingleOrDefaultAsync("dbo.usp_WorkflowRule_SaveValidated",StoredProcedureResult.FromReader,[I("@WorkflowRuleId",SqlDbType.BigInt,id),I("@RuleCode",SqlDbType.VarChar,x.Code.Trim(),40),I("@RuleName",SqlDbType.NVarChar,x.Name.Trim(),200),I("@AssetId",SqlDbType.BigInt,x.AssetId),I("@ReqType",SqlDbType.VarChar,x.RequisitionType.Trim().ToUpperInvariant(),20),I("@MinAmount",SqlDbType.Decimal,x.MinimumAmount),I("@MaxAmount",SqlDbType.Decimal,x.MaximumAmount),I("@ConcernDivisionId",SqlDbType.BigInt,x.ConcernDivisionId),I("@AuthorityBeforeDivision",SqlDbType.Bit,x.AuthorityBeforeDivision),I("@DestinationAfterConcern",SqlDbType.VarChar,x.DestinationAfterConcern.Trim().ToUpperInvariant(),30),I("@PriorityOrder",SqlDbType.Int,x.PriorityOrder),I("@IsActive",SqlDbType.Bit,x.IsActive),I("@EffectiveFrom",SqlDbType.Date,x.EffectiveFrom),I("@EffectiveTo",SqlDbType.Date,x.EffectiveTo),I("@Actor",SqlDbType.VarChar,actor,50)],c);
 public Task<WorkflowEvaluationDto?> EvaluateAsync(EvaluateWorkflowRuleRequest x,CancellationToken c)=>StoredProcedures.QuerySingleOrDefaultAsync("dbo.usp_WorkflowRule_Evaluate",r=>{var rule=MapEnriched(r);var division=rule.ConcernDivisionId is long id?new ConcernDivisionReferenceDto(id,rule.ConcernDivisionCode,rule.ConcernDivisionName):null;return new WorkflowEvaluationDto(rule,division,rule.AuthorityBeforeDivision,rule.DestinationAfterConcern,r.GetString(r.GetOrdinal("CALCULATED_ROUTE")));},[I("@AssetId",SqlDbType.BigInt,x.AssetId),I("@ReqType",SqlDbType.VarChar,x.RequisitionType.Trim().ToUpperInvariant(),20),I("@Amount",SqlDbType.Decimal,x.Amount),I("@AsOfDate",SqlDbType.Date,null)],c);
 private static WorkflowRuleDto MapEnriched(SqlDataReader r)=>new(r.GetInt64(r.GetOrdinal("WORKFLOW_RULE_ID")),r.GetString(r.GetOrdinal("RULE_CODE")),r.GetString(r.GetOrdinal("RULE_NAME")),r.GetInt64(r.GetOrdinal("ASSET_ID")),r.GetNullableString("ASSET_CODE"),r.GetNullableString("ASSET_NAME"),r.GetString(r.GetOrdinal("REQ_TYPE")),r.GetNullable<decimal>("MIN_AMOUNT"),r.GetNullable<decimal>("MAX_AMOUNT"),r.GetNullable<long>("CONCERN_DIVISION_ID"),r.GetNullableString("SETUP_CODE"),r.GetNullableString("CONCERN_DIVISION_NAME"),r.GetBoolean(r.GetOrdinal("AUTHORITY_BEFORE_DIVISION")),r.GetString(r.GetOrdinal("DESTINATION_AFTER_CONCERN")),r.GetInt32(r.GetOrdinal("PRIORITY_ORDER")),r.GetBoolean(r.GetOrdinal("IS_ACTIVE")),DateOnly.FromDateTime(r.GetDateTime(r.GetOrdinal("EFFECTIVE_FROM"))),r.GetNullable<DateTime>("EFFECTIVE_TO") is DateTime d?DateOnly.FromDateTime(d):null);
 private static WorkflowRuleDto MapBasic(SqlDataReader r)=>new(r.GetInt64(r.GetOrdinal("WORKFLOW_RULE_ID")),r.GetString(r.GetOrdinal("RULE_CODE")),r.GetString(r.GetOrdinal("RULE_NAME")),r.GetInt64(r.GetOrdinal("ASSET_ID")),null,null,r.GetString(r.GetOrdinal("REQ_TYPE")),r.GetNullable<decimal>("MIN_AMOUNT"),r.GetNullable<decimal>("MAX_AMOUNT"),r.GetNullable<long>("CONCERN_DIVISION_ID"),null,null,r.GetBoolean(r.GetOrdinal("AUTHORITY_BEFORE_DIVISION")),r.GetString(r.GetOrdinal("DESTINATION_AFTER_CONCERN")),r.GetInt32(r.GetOrdinal("PRIORITY_ORDER")),r.GetBoolean(r.GetOrdinal("IS_ACTIVE")),DateOnly.FromDateTime(r.GetDateTime(r.GetOrdinal("EFFECTIVE_FROM"))),r.GetNullable<DateTime>("EFFECTIVE_TO") is DateTime d?DateOnly.FromDateTime(d):null);
 private static SqlParameter I(string n,SqlDbType t,object? v,int? s=null)=>SqlParameterFactory.Input(n,t,v,s);
}
