using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class AssetSpecificationServiceTests
{
 public static void SupportedTypesAndOrderingValidate(){var s=New(out _);foreach(var t in new[]{"TEXT","NUMBER","DATE","DROPDOWN","MULTI_SELECT","YES_NO"})s.CreateAsync(1,new(){Name="Spec",Type=t},default).GetAwaiter().GetResult();TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(1,new(){Name="Spec",Type="FILE"},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(1,new(){Name="Spec",Type="TEXT",DisplayOrder=-1},default).GetAwaiter().GetResult());}
 public static void WritesUseCurrentEmployee(){var s=New(out var r);s.CreateOptionAsync(3,new(){Value="Red"},default).GetAwaiter().GetResult();TestAssert.Equal("EMP-ADMIN",r.Actor!);}
 public static void EmptyOptionsAndValuesValidate(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.CreateOptionAsync(1,new(){Value=" "},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.UpdateOptionsAsync(1,[],default).GetAwaiter().GetResult());}
 private static AssetSpecificationService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"EMP-ADMIN";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"";public IReadOnlyCollection<string> Roles=>["ADMIN"];public bool IsInRole(string x)=>true;}
 private sealed class Repo:IAssetSpecificationRepository
 {public string? Actor;private static Task<StoredProcedureResult?> R()=>Task.FromResult<StoredProcedureResult?>(new("000","Success",1,null));public Task<AssetSpecificationSetDto> GetByAssetAsync(long id,CancellationToken c)=>Task.FromResult(new AssetSpecificationSetDto(id,[]));public Task<StoredProcedureResult?> CreateAsync(long i,SaveAssetSpecificationRequest x,string a,CancellationToken c){Actor=a;return R();}public Task<StoredProcedureResult?> UpdateAsync(long i,SaveAssetSpecificationRequest x,string a,CancellationToken c){Actor=a;return R();}public Task<StoredProcedureResult?> CreateOptionAsync(long i,CreateAssetSpecificationOptionRequest x,string a,CancellationToken c){Actor=a;return R();}public Task<StoredProcedureResult?> UpdateOptionAsync(long i,UpdateAssetSpecificationOptionRequest x,string a,CancellationToken c){Actor=a;return R();}}
}
