using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class ConcernDivisionSetupServiceTests
{
 public static void OfficialsAndAuthoritiesRemainSeparate(){var s=New(out var r);s.GetOfficialsAsync(1,true,default).GetAwaiter().GetResult();TestAssert.Equal("officials",r.LastRead!);s.GetAuthoritiesAsync(1,true,default).GetAwaiter().GetResult();TestAssert.Equal("authorities",r.LastRead!);}
 public static void DevelopmentEmployeesAndDatesValidate(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.AddOfficialAsync(1,new(){EmployeeId="UNKNOWN"},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.AddOfficialAsync(1,new(){EmployeeId="DEV-USER",EffectiveFrom=new(2026,2,1),EffectiveTo=new(2026,1,1)},default).GetAwaiter().GetResult());}
 public static void MappingWritesUseCurrentEmployee(){var s=New(out var r);s.AddOfficialAsync(1,new(){EmployeeId="DEV-USER"},default).GetAwaiter().GetResult();TestAssert.Equal("ADMIN-1",r.Actor!);s.AddAuthorityAsync(1,new(){EmployeeId="DEV-USER",AuthorityLevel=2},default).GetAwaiter().GetResult();TestAssert.Equal("authority",r.LastWrite!);}
 private static ConcernDivisionSetupService New(out Repo r){r=new();return new(r,new Employees(),new User());}
 private sealed class Employees:IDevelopmentEmployeeResolver{public DevelopmentEmployeeDto? FindByEmployeeId(string id)=>id=="DEV-USER"?new(id,"Dev User","dev@test","Officer",1,"ICT"):null;public IReadOnlyList<DevelopmentEmployeeDto> Search(string? search)=>[];}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"ADMIN-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"ICT";public IReadOnlyCollection<string> Roles=>["ADMIN"];public bool IsInRole(string role)=>role=="ADMIN";}
 private sealed class Repo:IConcernDivisionSetupRepository
 {public string? LastRead;public string? LastWrite;public string? Actor;private static Task<StoredProcedureResult?> R()=>Task.FromResult<StoredProcedureResult?>(new("000","Success",1,null));public Task<IReadOnlyList<ConcernDivisionDto>> GetDivisionsAsync(bool a,CancellationToken c)=>Task.FromResult<IReadOnlyList<ConcernDivisionDto>>([]);public Task<IReadOnlyList<ConcernOfficialDto>> GetOfficialsAsync(long i,bool a,CancellationToken c){LastRead="officials";return Task.FromResult<IReadOnlyList<ConcernOfficialDto>>([]);}public Task<IReadOnlyList<ConcernAuthorityDto>> GetAuthoritiesAsync(long i,bool a,CancellationToken c){LastRead="authorities";return Task.FromResult<IReadOnlyList<ConcernAuthorityDto>>([]);}public Task<StoredProcedureResult?> AddOfficialAsync(long i,AddConcernOfficialRequest x,string a,CancellationToken c){Actor=a;LastWrite="official";return R();}public Task<StoredProcedureResult?> DeactivateOfficialAsync(long i,string a,CancellationToken c){Actor=a;return R();}public Task<StoredProcedureResult?> AddAuthorityAsync(long i,AddConcernAuthorityRequest x,string a,CancellationToken c){Actor=a;LastWrite="authority";return R();}public Task<StoredProcedureResult?> DeactivateAuthorityAsync(long i,string a,CancellationToken c){Actor=a;return R();}}
}
