using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class ConcernDivisionWorkflowServiceTests
{
 public static void QueueAndActionsUseAuthenticatedOfficial(){var s=New(out var r);s.GetPendingAsync(default).GetAwaiter().GetResult();s.VerifyCompleteAsync(1,null,default).GetAwaiter().GetResult();s.ForwardAuthorityAsync(1,"forward",default).GetAwaiter().GetResult();TestAssert.Equal("CO-1",r.Employee!);TestAssert.Equal("forward",r.Action!);}
 public static void ReturnAndNotRecommendRequireRemarks(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.ReturnAsync(1," ",default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.NotRecommendAsync(1,null,default).GetAwaiter().GetResult());}
 public static void OfficialChoicesRemainDistinct(){var s=New(out var r);s.ReturnAsync(2,"clarify",default).GetAwaiter().GetResult();TestAssert.Equal("return",r.Action!);s.NotRecommendAsync(2,"unsupported",default).GetAwaiter().GetResult();TestAssert.Equal("not-recommend",r.Action!);}
 public static void VerifyCompleteReturnsMatrixDestination(){var s=New(out var r);r.Result=new("000","Success",1,"PROCUREMENT_AUTHORITY");var x=s.VerifyCompleteAsync(1,null,default).GetAwaiter().GetResult();TestAssert.Equal("PROCUREMENT_AUTHORITY",x!.ReferenceNo!);}
 private static ConcernDivisionWorkflowService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"CO-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>9;public string OrgUnitCode=>"DIV";public IReadOnlyCollection<string>Roles=>["CONCERN_OFFICIAL"];public bool IsInRole(string x)=>x=="CONCERN_OFFICIAL";}
 private sealed class Repo:IConcernDivisionWorkflowRepository{public string?Employee;public string?Action;public StoredProcedureResult Result=new("000","Success",1,"READY_FOR_PROCUREMENT");private Task<StoredProcedureResult?>R(string a,string e){Action=a;Employee=e;return Task.FromResult<StoredProcedureResult?>(Result);}public Task<IReadOnlyList<ConcernDivisionPendingDto>>GetPendingAsync(string e,CancellationToken c){Employee=e;return Task.FromResult<IReadOnlyList<ConcernDivisionPendingDto>>([]);}public Task<StoredProcedureResult?>VerifyCompleteAsync(long i,string e,string?m,CancellationToken c)=>R("verify",e);public Task<StoredProcedureResult?>ForwardAuthorityAsync(long i,string e,string?m,CancellationToken c)=>R("forward",e);public Task<StoredProcedureResult?>ReturnAsync(long i,string e,string m,CancellationToken c)=>R("return",e);public Task<StoredProcedureResult?>NotRecommendAsync(long i,string e,string m,CancellationToken c)=>R("not-recommend",e);}
}
