using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class ManagerWorkflowServiceTests
{
 public static void PendingAndDetailUseCurrentManager(){var s=New(out var r);s.GetPendingAsync(default).GetAwaiter().GetResult();TestAssert.Equal("MGR-1",r.Employee!);s.GetDetailAsync(8,default).GetAwaiter().GetResult();TestAssert.Equal(8L,r.Id);TestAssert.Equal("MGR-1",r.Employee!);}
 public static void ReturnAndRejectRequireRemarks(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.ReturnAsync(1," ",default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.RejectAsync(1,null,default).GetAwaiter().GetResult());}
 public static void TransitionsUseTrustedActorAndDistinctActions(){var s=New(out var r);s.ApproveAsync(2,null,default).GetAwaiter().GetResult();TestAssert.Equal("approve",r.Action!);s.ReturnAsync(2,"Fix",default).GetAwaiter().GetResult();TestAssert.Equal("return",r.Action!);s.RejectAsync(2,"Invalid",default).GetAwaiter().GetResult();TestAssert.Equal("reject",r.Action!);TestAssert.Equal("MGR-1",r.Employee!);}
 private static ManagerWorkflowService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"MGR-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>6;public string OrgUnitCode=>"B1";public IReadOnlyCollection<string>Roles=>["MANAGER"];public bool IsInRole(string x)=>x=="MANAGER";}
 private sealed class Repo:IManagerWorkflowRepository
 {public string?Employee;public string?Action;public long Id;private static Task<StoredProcedureResult?>R()=>Task.FromResult<StoredProcedureResult?>(new("000","Success",1,null));public Task<IReadOnlyList<ManagerPendingRequisitionDto>>GetPendingAsync(string e,CancellationToken c){Employee=e;return Task.FromResult<IReadOnlyList<ManagerPendingRequisitionDto>>([]);}public Task<RequisitionDetailDto?>GetDetailAsync(long i,string e,CancellationToken c){Id=i;Employee=e;return Task.FromResult<RequisitionDetailDto?>(null);}public Task<StoredProcedureResult?>ApproveAsync(long i,string e,string?m,CancellationToken c){Id=i;Employee=e;Action="approve";return R();}public Task<StoredProcedureResult?>ReturnAsync(long i,string e,string m,CancellationToken c){Id=i;Employee=e;Action="return";return R();}public Task<StoredProcedureResult?>RejectAsync(long i,string e,string m,CancellationToken c){Id=i;Employee=e;Action="reject";return R();}}
}
