using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class ProcurementTrackingServiceTests
{
 public static void SearchUsesOnlyRequestedSimpleFilters(){var s=New(out var r);s.SearchAsync(" REQ ",4,7," delivered ",default).GetAwaiter().GetResult();TestAssert.Equal("REQ",r.RequisitionNo!);TestAssert.Equal(4L,r.OrgUnitId!.Value);TestAssert.Equal(7L,r.AssetId!.Value);TestAssert.Equal("DELIVERED",r.Status!);}
 public static void SingleUpdateUsesAuthenticatedTrackerAndOneId(){var s=New(out var r);s.UpdateStatusAsync(new(){RequisitionIds=[2],NewStatusCode="delivered",StatusDate=DateTime.UtcNow},default).GetAwaiter().GetResult();TestAssert.Equal("TRACK-1",r.Employee!);TestAssert.Equal("DELIVERED",r.Status!);TestAssert.True(r.Batch is null);TestAssert.Throws<ArgumentException>(()=>s.UpdateStatusAsync(new(){RequisitionIds=[1,2],NewStatusCode="DELIVERED",StatusDate=DateTime.UtcNow},default).GetAwaiter().GetResult());}
 public static void BulkUsesSharedBatchAndWritesEveryRequisition(){var s=New(out var r);r.Results[2]=new("002","Missing",2,null);var x=s.BulkUpdateStatusAsync(new(){RequisitionIds=[1,2,3],NewStatusCode="RFQ_INITIATED",StatusDate=DateTime.UtcNow},default).GetAwaiter().GetResult();TestAssert.Equal(3,r.UpdatedIds.Count);TestAssert.True(r.Batches.All(b=>b==x.BatchReferenceId));TestAssert.Equal(2,x.SuccessfulCount);TestAssert.Equal(1,x.FailedCount);}
 public static void InvalidStatusDateAndIdsAreRejected(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.BulkUpdateStatusAsync(new(){RequisitionIds=[0],NewStatusCode="DELIVERED",StatusDate=DateTime.UtcNow},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.BulkUpdateStatusAsync(new(){RequisitionIds=[1],NewStatusCode="DELIVERED",StatusDate=DateTime.UtcNow.AddDays(1)},default).GetAwaiter().GetResult());}
 private static ProcurementTrackingService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"TRACK-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"HO";public IReadOnlyCollection<string>Roles=>["PROCUREMENT_TRACKER"];public bool IsInRole(string x)=>x=="PROCUREMENT_TRACKER";}
 private sealed class Repo:IProcurementTrackingRepository{public string?RequisitionNo;public long?OrgUnitId;public long?AssetId;public string?Status;public string?Employee;public Guid?Batch;public List<Guid?>Batches=[];public List<long>UpdatedIds=[];public Dictionary<long,StoredProcedureResult>Results=[];public Task<IReadOnlyList<ProcurementTrackingSearchDto>>SearchAsync(string?n,long?o,long?a,string?s,CancellationToken c){RequisitionNo=n;OrgUnitId=o;AssetId=a;Status=s;return Task.FromResult<IReadOnlyList<ProcurementTrackingSearchDto>>([new(1,1,"REQ-1","HO","Laptop","READY_FOR_PROCUREMENT","Ready",null,DateTime.UtcNow),new(2,2,"REQ-2","HO","Laptop","READY_FOR_PROCUREMENT","Ready",null,DateTime.UtcNow),new(3,3,"REQ-3","HO","Laptop","READY_FOR_PROCUREMENT","Ready",null,DateTime.UtcNow)]);}public Task<ProcurementTrackingDetailDto?>GetAsync(long id,CancellationToken c)=>Task.FromResult<ProcurementTrackingDetailDto?>(null);public Task<StoredProcedureResult?>UpdateStatusAsync(long id,string s,DateTime d,string?r,string?m,string e,Guid?b,CancellationToken c){UpdatedIds.Add(id);Batches.Add(b);Batch=b;Status=s;Employee=e;return Task.FromResult<StoredProcedureResult?>(Results.GetValueOrDefault(id,new("000","Success",id,s)));}}
}
