using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class ProcurementAuthorityServiceTests
{
 public static void QueueAndActionsUseAuthenticatedAuthority(){var s=New(out var r);s.GetPendingAsync(default).GetAwaiter().GetResult();s.ApproveAsync(1,null,default).GetAwaiter().GetResult();s.ForwardAsync(2,"go",default).GetAwaiter().GetResult();TestAssert.Equal("PA-1",r.Employee!);TestAssert.Equal("forward",r.Action!);}
 public static void RejectRequiresRemarks(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.RejectAsync(1," ",default).GetAwaiter().GetResult());}
 public static void BulkUsesOneBatchAndProcessesFailuresIndependently(){var s=New(out var r);r.Results[2]=new("004","Already acted",2,null);var x=s.BulkApproveAsync(new(){RequisitionIds=[1,2,3],Remarks="approved"},default).GetAwaiter().GetResult();TestAssert.Equal(3,x.TotalSelected);TestAssert.Equal(2,x.SuccessfulCount);TestAssert.Equal(1,x.FailedCount);TestAssert.Equal(3,r.BatchIds.Count);TestAssert.True(r.BatchIds.All(b=>b==x.BatchReferenceId));TestAssert.Equal("REQ-2",x.Results[1].RequisitionNo!);}
 public static void BulkDeduplicatesIdsAndReturnsDatabaseDestination(){var s=New(out var r);r.Results[1]=new("000","Success",1,"CONCERN_DIVISION");var x=s.BulkApproveAsync(new(){RequisitionIds=[1,1]},default).GetAwaiter().GetResult();TestAssert.Equal(1,x.TotalSelected);TestAssert.Equal("CONCERN_DIVISION",x.Results[0].NextDestination!);}
 private static ProcurementAuthorityService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"PA-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"HO";public IReadOnlyCollection<string>Roles=>["PROCUREMENT_AUTHORITY"];public bool IsInRole(string x)=>x=="PROCUREMENT_AUTHORITY";}
 private sealed class Repo:IProcurementAuthorityRepository{public string?Employee;public string?Action;public Dictionary<long,StoredProcedureResult>Results=new();public List<Guid?>BatchIds=[];public Task<IReadOnlyList<ProcurementAuthorityPendingDto>>GetPendingAsync(string e,CancellationToken c){Employee=e;return Task.FromResult<IReadOnlyList<ProcurementAuthorityPendingDto>>([new(1,"REQ-1",DateTime.UtcNow,10,"Maker",1),new(2,"REQ-2",DateTime.UtcNow,20,"Maker",1),new(3,"REQ-3",DateTime.UtcNow,30,"Maker",1)]);}public Task<StoredProcedureResult?>ApproveAsync(long id,string e,string?m,Guid?b,CancellationToken c){Employee=e;Action="approve";BatchIds.Add(b);return Task.FromResult<StoredProcedureResult?>(Results.GetValueOrDefault(id,new("000","Success",id,"READY_FOR_PROCUREMENT")));}public Task<StoredProcedureResult?>RejectAsync(long id,string e,string m,CancellationToken c){Employee=e;Action="reject";return Task.FromResult<StoredProcedureResult?>(new("000","Success",id,"END"));}public Task<StoredProcedureResult?>ForwardAsync(long id,string e,string?m,CancellationToken c){Employee=e;Action="forward";return Task.FromResult<StoredProcedureResult?>(new("000","Success",id,"CONCERN_DIVISION"));}}
}
