using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class ProcurementOfficerAssetMappingServiceTests
{
 public static void ReturnsMultipleOfficerMappings(){var s=New(out _);var x=s.GetByAssetAsync(7,true,default).GetAwaiter().GetResult();TestAssert.Equal(2,x.Count);TestAssert.True(x[0].IsPrimary);TestAssert.False(x[1].IsPrimary);}
 public static void AddValidatesEmployeeAndDates(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.AddAsync(7,new(){EmployeeId="UNKNOWN"},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.AddAsync(7,new(){EmployeeId="DEV-PO",EffectiveFrom=new(2026,2,1),EffectiveTo=new(2026,1,1)},default).GetAwaiter().GetResult());}
 public static void WritesUseActorAndAssetScope(){var s=New(out var r);s.AddAsync(7,new(){EmployeeId="DEV-PO",IsPrimary=true},default).GetAwaiter().GetResult();TestAssert.Equal("ADMIN-1",r.Actor!);s.DeactivateAsync(7,9,default).GetAwaiter().GetResult();TestAssert.Equal(7L,r.AssetId);TestAssert.Equal(9L,r.MappingId);}
 private static ProcurementOfficerAssetMappingService New(out Repo r){r=new();return new(r,new Employees(),new User());}
 private sealed class Employees:IDevelopmentEmployeeResolver{public DevelopmentEmployeeDto? FindByEmployeeId(string id)=>id=="DEV-PO"?new(id,"Officer","po@test","PO",1,"ICT"):null;public IReadOnlyList<DevelopmentEmployeeDto> Search(string? search)=>[];}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"ADMIN-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"ICT";public IReadOnlyCollection<string> Roles=>["ADMIN"];public bool IsInRole(string r)=>r=="ADMIN";}
 private sealed class Repo:IProcurementOfficerAssetMappingRepository
 {public string? Actor;public long AssetId;public long MappingId;private static Task<StoredProcedureResult?> R()=>Task.FromResult<StoredProcedureResult?>(new("000","Success",1,null));public Task<IReadOnlyList<ProcurementOfficerAssetMappingDto>> GetByAssetAsync(long id,bool a,CancellationToken c)=>Task.FromResult<IReadOnlyList<ProcurementOfficerAssetMappingDto>>([new(1,id,"PO-1","One",null,null,true,new(2026,1,1),null,true),new(2,id,"PO-2","Two",null,null,false,new(2026,1,1),null,true)]);public Task<StoredProcedureResult?> AddAsync(long id,AddProcurementOfficerAssetMappingRequest x,string a,CancellationToken c){Actor=a;AssetId=id;return R();}public Task<StoredProcedureResult?> DeactivateAsync(long assetId,long mappingId,string a,CancellationToken c){Actor=a;AssetId=assetId;MappingId=mappingId;return R();}}
}
