using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class ProcurementOfficerWorkflowServiceTests
{
 public static void QueueAndActionsUseAuthenticatedOfficer(){var s=New(out var r);s.GetAssignedAsync(default).GetAwaiter().GetResult();s.TakeAsync(4,null,default).GetAwaiter().GetResult();s.ApproveAsync(4,"ok",default).GetAwaiter().GetResult();TestAssert.Equal("PO-7",r.Employee!);TestAssert.Equal("approve",r.Action!);}
 public static void ReturnRejectAndCommentsRequireContent(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.ReturnAsync(1," ",default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.RejectAsync(1,null,default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.AddCommentAsync(1,new(){CommentText=" "},default).GetAwaiter().GetResult());}
 public static void CommentAndTransitionsUseDistinctRepositoryOperations(){var s=New(out var r);s.ReturnAsync(2,"fix",default).GetAwaiter().GetResult();TestAssert.Equal("return",r.Action!);s.RejectAsync(2,"bad",default).GetAwaiter().GetResult();TestAssert.Equal("reject",r.Action!);s.AddCommentAsync(2,new(){RequisitionItemId=3,CommentText=" note "},default).GetAwaiter().GetResult();TestAssert.Equal("comment",r.Action!);TestAssert.Equal("note",r.Text!);TestAssert.Equal("PO-7",r.Employee!);}
 public static void ApprovalReturnsDatabaseCalculatedDestination(){var s=New(out var r);r.Result=new("000","Success",8,"CONCERN_DIVISION");var x=s.ApproveAsync(8,null,default).GetAwaiter().GetResult();TestAssert.Equal("CONCERN_DIVISION",x!.ReferenceNo!);}
 private static ProcurementOfficerWorkflowService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"PO-7";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"HO";public IReadOnlyCollection<string>Roles=>["PROCUREMENT_OFFICER"];public bool IsInRole(string x)=>x=="PROCUREMENT_OFFICER";}
 private sealed class Repo:IProcurementOfficerWorkflowRepository{public string?Employee;public string?Action;public string?Text;public StoredProcedureResult Result=new("000","Success",1,"READY_FOR_PROCUREMENT");private Task<StoredProcedureResult?>R(string a,string e){Action=a;Employee=e;return Task.FromResult<StoredProcedureResult?>(Result);}public Task<IReadOnlyList<ProcurementOfficerRequisitionDto>>GetAssignedAsync(string e,CancellationToken c){Employee=e;return Task.FromResult<IReadOnlyList<ProcurementOfficerRequisitionDto>>([]);}public Task<StoredProcedureResult?>TakeAsync(long i,string e,string?m,CancellationToken c)=>R("take",e);public Task<StoredProcedureResult?>ApproveAsync(long i,string e,string?m,CancellationToken c)=>R("approve",e);public Task<StoredProcedureResult?>ReturnAsync(long i,string e,string m,CancellationToken c)=>R("return",e);public Task<StoredProcedureResult?>RejectAsync(long i,string e,string m,CancellationToken c)=>R("reject",e);public Task<StoredProcedureResult?>AddCommentAsync(long i,long?item,string text,string e,CancellationToken c){Text=text;return R("comment",e);}}
}
