using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class RequisitionMakerServiceTests
{
 public static void SupportsMultipleItemsAndTrustedRequesterContext(){var s=New(out var r);s.CreateAsync(Valid(),default).GetAwaiter().GetResult();TestAssert.Equal(2,r.Saved!.Items.Count);TestAssert.Equal("MAKER-1",r.Employee!);TestAssert.Equal(6L,r.OrgUnit);}
 public static void ReplacementAndDynamicOptionValidation(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(Valid(false),default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(Valid(true,true),default).GetAwaiter().GetResult());}
 public static void ReadsAndSubmitUseAuthenticatedEmployee(){var s=New(out var r);s.GetMineAsync(default).GetAwaiter().GetResult();TestAssert.Equal("MAKER-1",r.Employee!);s.SubmitAsync(9,"Ready",default).GetAwaiter().GetResult();TestAssert.Equal(9L,r.Id);TestAssert.Equal("MAKER-1",r.Employee!);}
 private static SaveRequisitionRequest Valid(bool condition=true,bool duplicateOptions=false)=>new(){Justification="Need equipment",Items=[new(){AssetId=1,RequisitionType="NEW",Quantity=1,EstimatedUnitPrice=10,PurposeJustification="New user",DynamicSpecifications=duplicateOptions?[new(){SpecId=1,OptionIds=[2,2]}]:[]},new(){AssetId=2,RequisitionType="REPLACEMENT",Quantity=1,EstimatedUnitPrice=20,PurposeJustification="Broken",ReplacementInfo=new(){CurrentCondition=condition?"Failed":""}}]};
 private static RequisitionMakerService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"MAKER-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>6;public string OrgUnitCode=>"B1";public IReadOnlyCollection<string>Roles=>["MAKER"];public bool IsInRole(string x)=>x=="MAKER";}
 private sealed class Repo:IRequisitionMakerRepository
 {public SaveRequisitionRequest?Saved;public string?Employee;public long OrgUnit;public long Id;private static Task<StoredProcedureResult?>R()=>Task.FromResult<StoredProcedureResult?>(new("000","Success",1,"REQ"));public Task<StoredProcedureResult?>SaveAsync(long?i,SaveRequisitionRequest x,string e,long o,CancellationToken c){Saved=x;Employee=e;OrgUnit=o;return R();}public Task<RequisitionDetailDto?>GetAsync(long i,string e,CancellationToken c){Employee=e;Id=i;return Task.FromResult<RequisitionDetailDto?>(null);}public Task<IReadOnlyList<RequisitionSummaryDto>>GetMineAsync(string e,CancellationToken c){Employee=e;return Task.FromResult<IReadOnlyList<RequisitionSummaryDto>>([]);}public Task<StoredProcedureResult?>SubmitAsync(long i,string e,string?m,CancellationToken c){Id=i;Employee=e;return R();}}
}
