using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class SupportingServiceTests
{
 public static void AttachmentAndCommentActorsComeFromCurrentUser(){var s=New(out var r);s.AddAttachmentAsync(new(){EntityType="requisition",EntityId=1,FileName="a.pdf",OriginalFileName="a.pdf",StorageKey="bucket/a",FileSize=4},default).GetAwaiter().GetResult();TestAssert.Equal("EMP-1",r.Employee!);s.AddCommentAsync(new(){RequisitionId=1,CommentType="general",CommentText="note"},default).GetAwaiter().GetResult();TestAssert.Equal("EMP-1",r.Employee!);}
 public static void AttachmentStoresMetadataReferenceOnly(){var s=New(out var r);s.AddAttachmentAsync(new(){EntityType="WORK_ORDER",EntityId=2,FileName="wo.pdf",OriginalFileName="wo.pdf",StorageKey="object/wo.pdf",MimeType="application/pdf",FileSize=10},default).GetAwaiter().GetResult();TestAssert.Equal("object/wo.pdf",r.Attachment!.StorageKey);}
 public static void InvalidMetadataAndCommentsAreRejected(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.AddAttachmentAsync(new(){EntityType="BAD",EntityId=1,FileName="a",OriginalFileName="a",StorageKey="x"},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.AddCommentAsync(new(){RequisitionId=1,CommentType="GENERAL",CommentText=" "},default).GetAwaiter().GetResult());}
 public static void HistoryAndAuditFiltersReachRepository(){var s=New(out var r);s.GetApprovalHistoryAsync(7,default).GetAwaiter().GetResult();TestAssert.Equal("approval",r.Action!);s.GetWorkflowHistoryAsync(7,default).GetAwaiter().GetResult();TestAssert.Equal("workflow",r.Action!);s.GetProcurementHistoryAsync(7,default).GetAwaiter().GetResult();TestAssert.Equal("procurement",r.Action!);s.GetAuditAsync(" WORK_ORDER_HEADER ",null,1,50,default).GetAwaiter().GetResult();TestAssert.Equal("WORK_ORDER_HEADER",r.Name!);}
 private static SupportingService New(out Repo r){r=new();return new(r,new User());}private sealed class User:ICurrentUserService{public string EmployeeId=>"EMP-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"HO";public IReadOnlyCollection<string>Roles=>["MAKER"];public bool IsInRole(string x)=>false;}
 private sealed class Repo:ISupportingRepository{public string?Employee;public string?Action;public string?Name;public AddAttachmentMetadataRequest?Attachment;private static Task<StoredProcedureResult?>R()=>Task.FromResult<StoredProcedureResult?>(new("000","Success",1,null));public Task<StoredProcedureResult?>AddAttachmentAsync(AddAttachmentMetadataRequest x,string e,CancellationToken c){Attachment=x;Employee=e;return R();}public Task<IReadOnlyList<AttachmentMetadataDto>>GetAttachmentsAsync(string t,long i,CancellationToken c)=>Task.FromResult<IReadOnlyList<AttachmentMetadataDto>>([]);public Task<StoredProcedureResult?>AddCommentAsync(AddCommentRequest x,string e,CancellationToken c){Employee=e;return R();}public Task<IReadOnlyList<CommentDto>>GetCommentsAsync(long i,CancellationToken c)=>Task.FromResult<IReadOnlyList<CommentDto>>([]);public Task<IReadOnlyList<ApprovalHistoryDto>>GetApprovalHistoryAsync(long i,CancellationToken c){Action="approval";return Task.FromResult<IReadOnlyList<ApprovalHistoryDto>>([]);}public Task<IReadOnlyList<WorkflowHistoryDto>>GetWorkflowHistoryAsync(long i,CancellationToken c){Action="workflow";return Task.FromResult<IReadOnlyList<WorkflowHistoryDto>>([]);}public Task<IReadOnlyList<SupportingProcurementStatusHistoryDto>>GetProcurementHistoryAsync(long i,CancellationToken c){Action="procurement";return Task.FromResult<IReadOnlyList<SupportingProcurementStatusHistoryDto>>([]);}public Task<IReadOnlyList<AuditLogDto>>GetAuditAsync(string?n,long?i,int p,int s,CancellationToken c){Name=n;return Task.FromResult<IReadOnlyList<AuditLogDto>>([]);}}
}
