using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class WorkOrderServiceTests
{
 public static void MultipleRequisitionsAndActorReachRepository(){var s=New(out var r);s.CreateAsync(Valid(),default).GetAwaiter().GetResult();TestAssert.Equal("TRACK-1",r.Employee!);TestAssert.Equal(2,r.Request!.RequisitionIds.Count);}
 public static void HeaderAndDateValidationIsApplied(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(new(){RequisitionIds=[1],WorkOrderNo=" ",WorkOrderDate=DateOnly.FromDateTime(DateTime.Today),SupplierVendor="Vendor",WorkOrderValue=1},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(new(){RequisitionIds=[1],WorkOrderNo="WO",WorkOrderDate=new(2026,2,2),SupplierVendor="Vendor",WorkOrderValue=1,DeliveryDate=new(2026,2,1)},default).GetAwaiter().GetResult());}
 public static void ReadsValidateIds(){var s=New(out var r);s.GetAsync(5,default).GetAwaiter().GetResult();TestAssert.Equal(5L,r.Id);s.GetByRequisitionAsync(8,default).GetAwaiter().GetResult();TestAssert.Equal(8L,r.Id);TestAssert.Throws<ArgumentOutOfRangeException>(()=>s.GetAsync(0,default).GetAwaiter().GetResult());}
 private static CreateWorkOrderRequest Valid()=>new(){RequisitionIds=[1,2],WorkOrderNo="WO-1",WorkOrderDate=DateOnly.FromDateTime(DateTime.Today),SupplierVendor="Vendor",WorkOrderValue=100};private static WorkOrderService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"TRACK-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"HO";public IReadOnlyCollection<string>Roles=>["PROCUREMENT_TRACKER"];public bool IsInRole(string x)=>x=="PROCUREMENT_TRACKER";}
 private sealed class Repo:IWorkOrderRepository{public string?Employee;public CreateWorkOrderRequest?Request;public long Id;public Task<StoredProcedureResult?>CreateAsync(CreateWorkOrderRequest x,string e,CancellationToken c){Request=x;Employee=e;return Task.FromResult<StoredProcedureResult?>(new("000","Success",1,x.WorkOrderNo));}public Task<WorkOrderDto?>GetAsync(long id,CancellationToken c){Id=id;return Task.FromResult<WorkOrderDto?>(null);}public Task<IReadOnlyList<WorkOrderDto>>GetByRequisitionAsync(long id,CancellationToken c){Id=id;return Task.FromResult<IReadOnlyList<WorkOrderDto>>([]);}}
}
