using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Implementations;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Tests.Services;
public static class WorkflowRuleServiceTests
{
 public static void RuleValidationRejectsInvalidConfiguration(){var s=New(out _);TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(Valid() with{MinimumAmount=10,MaximumAmount=5},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(Valid() with{DestinationAfterConcern="CONCERN_AUTHORITY"},default).GetAwaiter().GetResult());TestAssert.Throws<ArgumentException>(()=>s.CreateAsync(Valid() with{AuthorityBeforeDivision=true,ConcernDivisionId=null},default).GetAwaiter().GetResult());}
 public static void WritesUseCurrentUserAndActivationPreservesRule(){var s=New(out var r);s.CreateAsync(Valid(),default).GetAwaiter().GetResult();TestAssert.Equal("ADMIN-1",r.Actor!);s.SetActiveAsync(1,false,default).GetAwaiter().GetResult();TestAssert.False(r.Saved!.IsActive);TestAssert.Equal("RULE-1",r.Saved.Code);}
 public static void EvaluationReturnsDatabaseCalculatedRoute(){var s=New(out _);var x=s.EvaluateAsync(new(){AssetId=4,RequisitionType="NEW",Amount=100},default).GetAwaiter().GetResult();TestAssert.Equal("DATABASE_ROUTE",x!.CalculatedRoute);}
 private static SaveWorkflowRuleRequest Valid()=>new(){Code="RULE-1",Name="Rule",AssetId=4,RequisitionType="NEW",DestinationAfterConcern="READY_FOR_PROCUREMENT",EffectiveFrom=new(2026,1,1)};
 private static WorkflowRuleService New(out Repo r){r=new();return new(r,new User());}
 private sealed class User:ICurrentUserService{public string EmployeeId=>"ADMIN-1";public string Email=>"";public string FullName=>"";public long OrgUnitId=>1;public string OrgUnitCode=>"ICT";public IReadOnlyCollection<string> Roles=>["ADMIN"];public bool IsInRole(string x)=>x=="ADMIN";}
 private sealed class Repo:IWorkflowRuleRepository
 {public string? Actor;public SaveWorkflowRuleRequest? Saved;private static WorkflowRuleDto Rule=>new(1,"RULE-1","Rule",4,"A","Asset","NEW",null,null,2,"CD","Division",false,"READY_FOR_PROCUREMENT",100,true,new(2026,1,1),null);public Task<IReadOnlyList<WorkflowRuleDto>> GetAllAsync(bool a,CancellationToken c)=>Task.FromResult<IReadOnlyList<WorkflowRuleDto>>([Rule]);public Task<WorkflowRuleDto?> GetByIdAsync(long i,CancellationToken c)=>Task.FromResult<WorkflowRuleDto?>(Rule);public Task<IReadOnlyList<WorkflowRuleDto>> GetByAssetAsync(long i,bool a,CancellationToken c)=>Task.FromResult<IReadOnlyList<WorkflowRuleDto>>([Rule]);public Task<StoredProcedureResult?> SaveAsync(long? i,SaveWorkflowRuleRequest x,string a,CancellationToken c){Actor=a;Saved=x;return Task.FromResult<StoredProcedureResult?>(new("000","Success",1,null));}public Task<WorkflowEvaluationDto?> EvaluateAsync(EvaluateWorkflowRuleRequest x,CancellationToken c)=>Task.FromResult<WorkflowEvaluationDto?>(new(Rule,new(2,"CD","Division"),false,"READY_FOR_PROCUREMENT","DATABASE_ROUTE"));}
}
