using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Routing;
namespace JamunaBank.Procurement.API.Extensions;
public static class ApplicationBuilderExtensions
{
 public static WebApplication UseApiFoundation(this WebApplication app){app.UseMiddleware<Middleware.GlobalExceptionHandlingMiddleware>();app.UseHttpsRedirection();app.UseCors(ServiceCollectionExtensions.CorsPolicyName);app.UseAuthentication();app.UseAuthorization();app.MapGet("/openapi/v1.json",(EndpointDataSource source)=>Results.Json(BuildOpenApi(source))).ExcludeFromDescription();app.MapGet("/swagger",()=>Results.Content(SwaggerPage,"text/html")).ExcludeFromDescription();return app;}
 private static object BuildOpenApi(EndpointDataSource source){var paths=new SortedDictionary<string,object>();var routes=source.Endpoints.OfType<RouteEndpoint>().Where(e=>e.RoutePattern.RawText?.StartsWith("api/",StringComparison.OrdinalIgnoreCase)==true);foreach(var group in routes.GroupBy(e=>"/"+e.RoutePattern.RawText)){var operations=new SortedDictionary<string,object>();foreach(var endpoint in group){var methods=endpoint.Metadata.GetMetadata<IHttpMethodMetadata>()?.HttpMethods??["GET"];var anonymous=endpoint.Metadata.GetMetadata<IAllowAnonymous>()is not null;foreach(var method in methods)operations[method.ToLowerInvariant()]=new{summary=endpoint.DisplayName??group.Key,security=anonymous?Array.Empty<object>():new object[]{new Dictionary<string,string[]>{{"Bearer",[]}}},responses=new Dictionary<string,object>{{"200",new{description="Success"}},{"400",new{description="Validation error"}},{"401",new{description="Authentication required"}},{"403",new{description="Forbidden"}},{"500",new{description="Server error"}}}};}paths[group.Key]=operations;}return new{openapi="3.0.1",info=new{title="Jamuna Bank Procurement API",version="v1"},components=new{securitySchemes=new{Bearer=new{type="http",scheme="bearer",bearerFormat="JWT"}}},paths};}
 private const string SwaggerPage="""<!doctype html><html><head><meta charset="utf-8"><title>Jamuna Bank Procurement API</title><link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css"></head><body><div id="swagger-ui"></div><script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script><script>SwaggerUIBundle({url:'/openapi/v1.json',dom_id:'#swagger-ui'});</script></body></html>""";
}
