using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Services.Implementations;
public sealed class RequisitionMakerService(IRequisitionMakerRepository repository,ICurrentUserService currentUser):IRequisitionMakerService
{
 private static readonly HashSet<string> Types=new(["NEW","REPLACEMENT","ADDITIONAL"],StringComparer.OrdinalIgnoreCase);
 public Task<StoredProcedureResult?> CreateAsync(SaveRequisitionRequest x,CancellationToken ct){Validate(x);return repository.SaveAsync(null,x,currentUser.EmployeeId,currentUser.OrgUnitId,ct);}
 public Task<StoredProcedureResult?> UpdateAsync(long id,SaveRequisitionRequest x,CancellationToken ct){Positive(id);Validate(x);return repository.SaveAsync(id,x,currentUser.EmployeeId,currentUser.OrgUnitId,ct);}
 public Task<RequisitionDetailDto?> GetAsync(long id,CancellationToken ct){Positive(id);return repository.GetAsync(id,currentUser.EmployeeId,ct);}
 public Task<IReadOnlyList<RequisitionSummaryDto>> GetMineAsync(CancellationToken ct)=>repository.GetMineAsync(currentUser.EmployeeId,ct);
 public Task<StoredProcedureResult?> SubmitAsync(long id,string? remarks,CancellationToken ct){Positive(id);if(remarks?.Length>2000)throw new ArgumentException("Remarks cannot exceed 2000 characters.");return repository.SubmitAsync(id,currentUser.EmployeeId,remarks,ct);}
 private static void Validate(SaveRequisitionRequest x){if(string.IsNullOrWhiteSpace(x.Justification))throw new ArgumentException("Justification is required.");if(x.Items.Count==0)throw new ArgumentException("At least one item is required.");foreach(var i in x.Items){Positive(i.AssetId);if(!Types.Contains(i.RequisitionType))throw new ArgumentException("Requisition type is invalid.");if(i.Quantity<=0||i.EstimatedUnitPrice<=0||string.IsNullOrWhiteSpace(i.PurposeJustification))throw new ArgumentException("Item quantity, estimated unit price, and purpose are required.");if(i.RequisitionType.Equals("REPLACEMENT",StringComparison.OrdinalIgnoreCase)){if(string.IsNullOrWhiteSpace(i.ReplacementInfo?.CurrentCondition))throw new ArgumentException("Current condition is required for replacement items.");}else if(i.ReplacementInfo is not null)throw new ArgumentException("Replacement information is allowed only for replacement items.");if(i.DynamicSpecifications.GroupBy(s=>s.SpecId).Any(g=>g.Count()>1))throw new ArgumentException("An item cannot contain duplicate specification IDs.");foreach(var s in i.DynamicSpecifications){Positive(s.SpecId);if(s.OptionIds.Any(id=>id<=0)||s.OptionIds.Count!=s.OptionIds.Distinct().Count())throw new ArgumentException("Specification option IDs must be positive and unique.");}}}
 private static void Positive(long id){if(id<=0)throw new ArgumentOutOfRangeException(nameof(id));}
}
