using JamunaBank.Procurement.API.DTOs;using JamunaBank.Procurement.API.Models;using JamunaBank.Procurement.API.Repositories.Interfaces;using JamunaBank.Procurement.API.Services.Interfaces;
namespace JamunaBank.Procurement.API.Services.Implementations;
public sealed class WorkflowRuleService(IWorkflowRuleRepository repository,ICurrentUserService currentUser):IWorkflowRuleService
{
 private static readonly HashSet<string> Types=new(["NEW","REPLACEMENT","ADDITIONAL"],StringComparer.OrdinalIgnoreCase);private static readonly HashSet<string> Destinations=new(["READY_FOR_PROCUREMENT","PROCUREMENT_AUTHORITY"],StringComparer.OrdinalIgnoreCase);
 public Task<IReadOnlyList<WorkflowRuleDto>> GetAllAsync(bool activeOnly,CancellationToken ct)=>repository.GetAllAsync(activeOnly,ct);
 public Task<WorkflowRuleDto?> GetByIdAsync(long id,CancellationToken ct){Positive(id);return repository.GetByIdAsync(id,ct);}
 public Task<IReadOnlyList<WorkflowRuleDto>> GetByAssetAsync(long id,bool activeOnly,CancellationToken ct){Positive(id);return repository.GetByAssetAsync(id,activeOnly,ct);}
 public Task<StoredProcedureResult?> CreateAsync(SaveWorkflowRuleRequest x,CancellationToken ct){Validate(x);return repository.SaveAsync(null,x,currentUser.EmployeeId,ct);}
 public Task<StoredProcedureResult?> UpdateAsync(long id,SaveWorkflowRuleRequest x,CancellationToken ct){Positive(id);Validate(x);return repository.SaveAsync(id,x,currentUser.EmployeeId,ct);}
 public async Task<StoredProcedureResult?> SetActiveAsync(long id,bool active,CancellationToken ct){var r=await GetByIdAsync(id,ct);if(r is null)return new("002","Not found",id,null);return await UpdateAsync(id,new(){Code=r.Code,Name=r.Name,AssetId=r.AssetId,RequisitionType=r.RequisitionType,MinimumAmount=r.MinimumAmount,MaximumAmount=r.MaximumAmount,ConcernDivisionId=r.ConcernDivisionId,AuthorityBeforeDivision=r.AuthorityBeforeDivision,DestinationAfterConcern=r.DestinationAfterConcern,PriorityOrder=r.PriorityOrder,IsActive=active,EffectiveFrom=r.EffectiveFrom,EffectiveTo=r.EffectiveTo},ct);}
 public Task<WorkflowEvaluationDto?> EvaluateAsync(EvaluateWorkflowRuleRequest x,CancellationToken ct){if(x.Amount<0)throw new ArgumentException("Amount cannot be negative.");ValidateType(x.AssetId,x.RequisitionType);return repository.EvaluateAsync(x,ct);}
 private static void Validate(SaveWorkflowRuleRequest x){if(string.IsNullOrWhiteSpace(x.Code)||string.IsNullOrWhiteSpace(x.Name))throw new ArgumentException("Rule code and name are required.");ValidateType(x.AssetId,x.RequisitionType);if(x.MinimumAmount<0||x.MaximumAmount<0||x.MaximumAmount<x.MinimumAmount)throw new ArgumentException("Amount range is invalid.");if(x.ConcernDivisionId<=0)throw new ArgumentException("Concern division ID must be positive when supplied.");if(x.AuthorityBeforeDivision&&x.ConcernDivisionId is null)throw new ArgumentException("Authority-before-division requires a concern division.");if(!Destinations.Contains(x.DestinationAfterConcern))throw new ArgumentException("Destination after concern must be READY_FOR_PROCUREMENT or PROCUREMENT_AUTHORITY.");if(x.PriorityOrder<0)throw new ArgumentException("Priority order cannot be negative.");if(x.EffectiveTo<x.EffectiveFrom)throw new ArgumentException("Effective-to date cannot precede effective-from date.");}
 private static void ValidateType(long assetId,string type){Positive(assetId);if(!Types.Contains(type))throw new ArgumentException("Requisition type must be NEW, REPLACEMENT, or ADDITIONAL.");}
 private static void Positive(long id){if(id<=0)throw new ArgumentOutOfRangeException(nameof(id));}
}
